#!/bin/bash

TARG=${1}
 
if [ -z "${TARG}" ]; then
  echo "[ERROR]: Please pass target materical descriptor, e.g. CH"
  exit 1
fi

TARG_N=""
TARG_Z=""
TARG_H=""
TARG_A=""

if [ "${TARG}" = "H" ]; then
  TARG_N="0"
  TARG_Z="1"
  TARG_H="0"
  TARG_A="1"
elif [ "${TARG}" = "D" ]; then
  TARG_N="1"
  TARG_Z="1"
  TARG_H="0"
  TARG_A="2"
elif [ "${TARG}" = "C" ]; then
  TARG_N="6"
  TARG_Z="6"
  TARG_H="0"
  TARG_A="12"
elif [ "${TARG}" = "CH" ]; then
  TARG_N="6"
  TARG_Z="6"
  TARG_H="1"
  TARG_A="12"
elif [ "${TARG}" = "CH2" ]; then
  TARG_N="6"
  TARG_Z="6"
  TARG_H="2"
  TARG_A="12"
elif [ "${TARG}" = "O" ]; then
  TARG_N="8"
  TARG_Z="8"
  TARG_H="0"
  TARG_A="16"
elif [ "${TARG}" = "H2O" ]; then
  TARG_N="8"
  TARG_Z="8"
  TARG_H="2"
  TARG_A="16"
elif [ "${TARG}" = "Cl" ]; then
  TARG_N="18"
  TARG_Z="17"
  TARG_H="0"
  TARG_A="35"
elif [ "${TARG}" = "Ar" ]; then
  TARG_N="22"
  TARG_Z="18"
  TARG_H="0"
  TARG_A="40"
elif [ "${TARG}" = "Fe" ]; then
  TARG_N="30"
  TARG_Z="26"
  TARG_H="0"
  TARG_A="56"
elif  [ "${TARG}" = "Pb" ]; then
  TARG_N="126"
  TARG_Z="82"
  TARG_H="0"
  TARG_A="208"
else
  echo "[ERROR]: Invalid target material: \"${TARG}\" for NEUT." 
fi

echo "${TARG_N}:${TARG_Z}:${TARG_H}:${TARG_A}"