#!/bin/bash

TARG=${1}

if [ -z "${TARG}" ]; then
  echo "[ERROR]: Please pass target materical descriptor, e.g. CH"
  exit 1
fi

if [ "${TARG}" = "H" ]; then
  echo "1000010010[1]"
elif [ "${TARG}" = "D" ]; then
  echo "1000010020[1]"
elif [ "${TARG}" = "C" ]; then
  echo "1000060120[1]"
elif [ "${TARG}" = "CH" ]; then
  echo "1000060120[.923076],1000010010[.076924]"
elif [ "${TARG}" = "CH2" ]; then
  echo "1000060120[.8571],1000010010[.14285]"
elif [ "${TARG}" = "O" ]; then
  echo "1000060120[1]"
elif [ "${TARG}" = "H2O" ]; then
  echo "1000080160[.888888],1000010010[.111112]"
elif [ "${TARG}" = "Ar" ]; then
  echo "1000180400[1]"
elif [ "${TARG}" = "Fe" ]; then
  echo "1000260560[1]"
elif  [ "${TARG}" = "Pb" ]; then
  echo "1000822080[1]"
else
  echo "[ERROR]: Invalid target material: \"${TARG}\" for NEUT." 
fi