#!/bin/bash

if [ -z ${NUISANCE} ]; then
  echo "[ERROR]: We need to be in a NUISANCE environment (\$NUISANCE should be set)."
  exit 1
fi

EXPERIMENT=""
PROBE="14"
BEAMMODE="nu"


while [[ ${#} -gt 0 ]]; do

  key="$1"
  case $key in

  -e|--experiment)

      if [[ ${#} -lt 2 ]]; then
        echo "[ERROR]: ${1} expected a value."
        exit 1
      fi

      EXPERIMENT="$2"
      shift # past argument
      ;;

  -p|--probe)

      if [[ ${#} -lt 2 ]]; then
        echo "[ERROR]: ${1} expected a value."
        exit 1
      fi

      PROBE="$2"
      shift # past argument
      ;;

  -m|--beam-mode)

      if [[ ${#} -lt 2 ]]; then
        echo "[ERROR]: ${1} expected a value."
        exit 1
      fi

      BEAMMODE="$2"
      shift # past argument
      ;;

  -AE|--all-experiments)

      echo -e "Experimental Fluxes Available:"
      echo -e "    ANL_77 (ANL)"
      echo -e "    ArgoNeut"
      echo -e "    BEBC"
      echo -e "    BNL_81"
      echo -e "    BNL_86"
      echo -e "    BNL_02 (BNL)"
      echo -e "    FNAL_82"
      echo -e "    FNAL_93 (FNAL)"
      echo -e "    GGM"
      echo -e "    K2K"
      echo -e "    MicroBooNE"
      echo -e "    MINERvA_LE (MINERvA)"
      echo -e "    MINERvA_ME"
      echo -e "    MiniBooNE"
      echo -e "    NOvA_ND"
      echo -e "    SciBooNE"
      echo -e "    T2K_ND"
      exit 0
      ;;

  -?|--help)
              # unknown option
      echo "Arguments:"
      echo -e "\tRequired:"
      echo -e "\t  -e|--experiment <experiment name>"
      echo -e "\tOptional:"
      echo -e "\t  -p|--probe <neutrino pdg>        : defaults to 14"
      echo -e "\t  -m|--beam-mode <nu/nubar>        : defaults to nu"
      echo -e "\t  -AE|--all-experiments            : List all experiments"
      echo -e "\t  -?|--help"
      exit 0
      ;;


      *)
              # unknown option
      echo "Unknown option $1"
      exit 1
      ;;
  esac
  shift
done

if [ -z "${EXPERIMENT}" ]; then
  echo "[ERROR]: No experiment requested, please pass experiment name with -e CLI option."
  exit 1
fi

if [ "${PROBE}" != "14" ] && [ "${PROBE}" != "-14" ] && [ "${PROBE}" != "12" ] \
  && [ "${PROBE}" != "-12" ]; then
    echo "[ERROR]: Invalid probe pdg requested, please use one of 14 (numu), -14, 12 (nue), or -12."
    exit 1
fi

case $EXPERIMENT in
  ANL)
    # Bash 4 fallthrough
    ;&
  ANL_77)
    if [ "${PROBE}" == "14" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/ANL_1977_2horn_rescan.root,numu_flux"
      exit 0
    fi
    ;;
  ArgoNeut)
    if [ "${PROBE}" == "14" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/ArgoNeut_numu_flux.root,numu"
      exit 0
    elif [ "${PROBE}" == "-14" ] && [ "${BEAMMODE}" == "nubar" ]; then
      echo "${NUISANCE}/data/flux/ArgoNeut_numub_flux.root,numub"
      exit 0
    fi
    ;;
  BEBC)
    if [ "${PROBE}" == "14" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/BEBC_Wachsmuth_numu_table.root,numu_flux"
      exit 0
    elif [ "${PROBE}" == "-14" ] && [ "${BEAMMODE}" == "nubar" ]; then
      echo "${NUISANCE}/data/flux/BEBC_Wachsmuth_numubar_table.root,numu_flux"
      exit 0
    fi
    ;;
  BNL_81)
    if [ "${PROBE}" == "14" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/BNL_CCQE_1981_rescan-ALTERNATIVE.root,numu_flux"
      exit 0
    fi
    ;;
  BNL_86)
    if [ "${PROBE}" == "14" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/BNL_1986_flux-ALTERNATIVE.root,numu_flux"
      exit 0
    fi
    ;;
  BNL)
    # Bash 4 fallthrough
    ;&
  BNL_02)
    if [ "${PROBE}" == "14" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/BNL_NuInt02_rescan.root,numu_flux"
      exit 0
    fi
    ;;
  FNAL_82)
    if [ "${PROBE}" == "14" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/FNAL_CCinc_1982_nu_MCadj.root,numu_flux"
      exit 0
    fi
    ;;
  FNAL)
    # Bash 4 fallthrough
    ;&
  FNAL_93)
    if [ "${PROBE}" == "-14" ] && [ "${BEAMMODE}" == "nubar" ]; then
      echo "${NUISANCE}/data/flux/FNAL_coh_1993_anu.root,numu_flux"
      exit 0
    fi
    ;;
  GGM)
    if [ "${PROBE}" == "14" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/GGM_nu_flux_1979_rescan.root,numu_flux"
      exit 0
    fi
    ;;
  K2K)
    if [ "${PROBE}" == "14" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/K2K_flux.root,numu_flux"
      exit 0
    fi
    ;;
  MicroBooNE)
    if [ "${PROBE}" == "14" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/MicroBooNE_CCInc2019_numode_numu_flux.root,flux_numu"
      exit 0
    fi
    ;;
  MINERvA)
    ;&
  MINERvA_LE)
    if [ "${PROBE}" == "14" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/minerva_le_flux.root,numu_fhc"
      exit 0
    elif [ "${PROBE}" == "-14" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/minerva_le_flux.root,numubar_fhc"
      exit 0
    elif [ "${PROBE}" == "12" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/minerva_le_flux.root,nue_fhc"
      exit 0
    elif [ "${PROBE}" == "-12" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/minerva_le_flux.root,nuebar_fhc"
      exit 0
    elif [ "${PROBE}" == "14" ] && [ "${BEAMMODE}" == "nubar" ]; then
      echo "${NUISANCE}/data/flux/minerva_le_flux.root,numu_rhc"
      exit 0
    elif [ "${PROBE}" == "-14" ] && [ "${BEAMMODE}" == "nubar" ]; then
      echo "${NUISANCE}/data/flux/minerva_le_flux.root,numubar_rhc"
      exit 0
    elif [ "${PROBE}" == "12" ] && [ "${BEAMMODE}" == "nubar" ]; then
      echo "${NUISANCE}/data/flux/minerva_le_flux.root,nue_rhc"
      exit 0
    elif [ "${PROBE}" == "-12" ] && [ "${BEAMMODE}" == "nubar" ]; then
      echo "${NUISANCE}/data/flux/minerva_le_flux.root,nuebar_rhc"
      exit 0
    fi
    ;;
  MINERvA_ME)
    if [ "${PROBE}" == "14" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/MINERvA_ME_Flux_No_Constraint.root,reweightedflux_rebinned_CV_WithStatErr"
      exit 0
    fi
    ;;
  MiniBooNE)
    if [ "${PROBE}" == "14" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/MiniBooNE_numu_flux.root,numu_mb"
      exit 0
    elif [ "${PROBE}" == "-14" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/MiniBooNE_numu_flux.root,numub_mb"
      exit 0
    elif [ "${PROBE}" == "12" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/MiniBooNE_numu_flux.root,nue_mb"
      exit 0
    elif [ "${PROBE}" == "-12" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/MiniBooNE_numu_flux.root,nueb_mb"
      exit 0
    elif [ "${PROBE}" == "14" ] && [ "${BEAMMODE}" == "nubar" ]; then
      echo "${NUISANCE}/data/flux/MiniBooNE_numubar_flux.root,numu_mb"
      exit 0
    elif [ "${PROBE}" == "-14" ] && [ "${BEAMMODE}" == "nubar" ]; then
      echo "${NUISANCE}/data/flux/MiniBooNE_numubar_flux.root,numub_mb"
      exit 0
    elif [ "${PROBE}" == "12" ] && [ "${BEAMMODE}" == "nubar" ]; then
      echo "${NUISANCE}/data/flux/MiniBooNE_numubar_flux.root,nue_mb"
      exit 0
    elif [ "${PROBE}" == "-12" ] && [ "${BEAMMODE}" == "nubar" ]; then
      echo "${NUISANCE}/data/flux/MiniBooNE_numubar_flux.root,nueb_mb"
      exit 0
    fi
    ;;
  NOvA_ND)
    if [ "${PROBE}" == "14" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/FHC_Flux_NOvA_ND_2017.root,flux_numu"
      exit 0
    elif [ "${PROBE}" == "-14" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/FHC_Flux_NOvA_ND_2017.root,flux_numubar"
      exit 0
    elif [ "${PROBE}" == "12" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/FHC_Flux_NOvA_ND_2017.root,flux_nue"
      exit 0
    elif [ "${PROBE}" == "-12" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/FHC_Flux_NOvA_ND_2017.root,flux_nuebar"
      exit 0
    fi
    ;;
  SciBooNE)
    if [ "${PROBE}" == "14" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/sciboone_fhc.root,flux_numu"
      exit 0
    fi
    ;;
  T2K_ND)
    if [ "${PROBE}" == "14" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/t2kflux_2016_plus250kA.root,enu_nd280_numu"
      exit 0
    elif [ "${PROBE}" == "-14" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/t2kflux_2016_plus250kA.root,enu_nd280_numub"
      exit 0
    elif [ "${PROBE}" == "12" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/t2kflux_2016_plus250kA.root,enu_nd280_nue"
      exit 0
    elif [ "${PROBE}" == "-12" ] && [ "${BEAMMODE}" == "nu" ]; then
      echo "${NUISANCE}/data/flux/t2kflux_2016_plus250kA.root,enu_nd280_nueb"
      exit 0
    elif [ "${PROBE}" == "14" ] && [ "${BEAMMODE}" == "nubar" ]; then
      echo "${NUISANCE}/data/flux/t2kflux_2016_minus250kA.root,enu_nd280_numu"
      exit 0
    elif [ "${PROBE}" == "-14" ] && [ "${BEAMMODE}" == "nubar" ]; then
      echo "${NUISANCE}/data/flux/t2kflux_2016_minus250kA.root,enu_nd280_numub"
      exit 0
    elif [ "${PROBE}" == "12" ] && [ "${BEAMMODE}" == "nubar" ]; then
      echo "${NUISANCE}/data/flux/t2kflux_2016_minus250kA.root,enu_nd280_nue"
      exit 0
    elif [ "${PROBE}" == "-12" ] && [ "${BEAMMODE}" == "nubar" ]; then
      echo "${NUISANCE}/data/flux/t2kflux_2016_minus250kA.root,enu_nd280_nueb"
      exit 0
    fi
    ;;
esac

echo "[ERROR]: Could not find flux for Experiment: \"${EXPERIMENT}\", in Mode: \"${BEAMMODE}\" for neutrino species pdg: \"${PROBE}\"."
exit 1