//
// File generated by rootcint at Fri Jul  8 11:20:14 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dIhomedIstowelldIt2krepdINIWGdIexternalDataFitterdIsrcdIANLdI_ROOT_DICT_ExternalDataFit_ANL
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "_ROOT_DICT_ExternalDataFit_ANL.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

/********************************************************
* /home/stowell/t2krep/NIWG/externalDataFitter/src/ANL/_ROOT_DICT_ExternalDataFit_ANL.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtable_ROOT_DICT_ExternalDataFit_ANL();

extern "C" void G__set_cpp_environment_ROOT_DICT_ExternalDataFit_ANL() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("ANL_CC1npip_Evt_1DcosmuStar_nu.h");
  G__add_compiledheader("ANL_CC1npip_Evt_1Dppi_nu.h");
  G__add_compiledheader("ANL_CC1npip_Evt_1DQ2_nu.h");
  G__add_compiledheader("ANL_CC1npip_XSec_1DEnu_nu.h");
  G__add_compiledheader("ANL_CC1pi0_Evt_1DcosmuStar_nu.h");
  G__add_compiledheader("ANL_CC1pi0_Evt_1DQ2_nu.h");
  G__add_compiledheader("ANL_CC1pi0_XSec_1DEnu_nu.h");
  G__add_compiledheader("ANL_CC1ppip_Evt_1DcosmuStar_nu.h");
  G__add_compiledheader("ANL_CC1ppip_Evt_1DcosthAdler_nu.h");
  G__add_compiledheader("ANL_CC1ppip_Evt_1Dphi_nu.h");
  G__add_compiledheader("ANL_CC1ppip_Evt_1Dppi_nu.h");
  G__add_compiledheader("ANL_CC1ppip_Evt_1DQ2_nu.h");
  G__add_compiledheader("ANL_CC1ppip_Evt_1Dthpr_nu.h");
  G__add_compiledheader("ANL_CC1ppip_XSec_1DEnu_nu.h");
  G__add_compiledheader("ANL_CC1ppip_XSec_1DQ2_nu.h");
  G__add_compiledheader("ANL_CCQE_Evt_1DQ2_nu.h");
  G__add_compiledheader("ANL_CCQE_XSec_1DEnu_nu.h");
  G__add_compiledheader("ANL_NC1npip_Evt_1Dppi_nu.h");
  G__cpp_reset_tagtable_ROOT_DICT_ExternalDataFit_ANL();
}
#include <new>
extern "C" int G__cpp_dllrev_ROOT_DICT_ExternalDataFit_ANL() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfunc_ROOT_DICT_ExternalDataFit_ANL {
 public:
  G__Sizep2memfunc_ROOT_DICT_ExternalDataFit_ANL(): p(&G__Sizep2memfunc_ROOT_DICT_ExternalDataFit_ANL::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfunc_ROOT_DICT_ExternalDataFit_ANL::*p)();
};

size_t G__get_sizep2memfunc_ROOT_DICT_ExternalDataFit_ANL()
{
  G__Sizep2memfunc_ROOT_DICT_ExternalDataFit_ANL a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritance_ROOT_DICT_ExternalDataFit_ANL() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetable_ROOT_DICT_ExternalDataFit_ANL() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSym<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSymlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTColumn_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTFlat_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSub_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTColumnlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTFlatlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSublEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TElementActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TElementPosActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparse<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<FitParticle>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEFitParticlecOallocatorlEFitParticlegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEFitParticlecOallocatorlEFitParticlegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEFitParticlecOallocatorlEFitParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEFitParticlecOallocatorlEFitParticlegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEFitParticlecOallocatorlEFitParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,std::string>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,std::string>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,string>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,string,less<string> >",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,int>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,int>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,double>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,double>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,bool>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,bool>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,bool>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,bool,less<string> >",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::string>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<t2krew::T2KSyst_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEt2krewcLcLET2KSystcOallocatorlEt2krewcLcLET2KSystgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEt2krewcLcLET2KSystcOallocatorlEt2krewcLcLET2KSystgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEt2krewcLcLET2KSystcOallocatorlEt2krewcLcLET2KSystgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEt2krewcLcLET2KSystcOallocatorlEt2krewcLcLET2KSystgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEt2krewcLcLET2KSystcOallocatorlEt2krewcLcLET2KSystgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<t2krew::ET2KSyst>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEt2krewcLcLET2KSystcOallocatorlEt2krewcLcLET2KSystgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<T2KSyst_t,T2KSystInfo*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEt2krewcLcLET2KSystcOt2krewcLcLT2KSystInfomUcOlesslEt2krewcLcLET2KSystgRcOallocatorlEpairlEconstsPt2krewcLcLET2KSystcOt2krewcLcLT2KSystInfomUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<t2krew::ET2KSyst,t2krew::T2KSystInfo*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEt2krewcLcLET2KSystcOt2krewcLcLT2KSystInfomUcOlesslEt2krewcLcLET2KSystgRcOallocatorlEpairlEconstsPt2krewcLcLET2KSystcOt2krewcLcLT2KSystInfomUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<t2krew::ET2KSyst,t2krew::T2KSystInfo*,less<t2krew::ET2KSyst> >",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEt2krewcLcLET2KSystcOt2krewcLcLT2KSystInfomUcOlesslEt2krewcLcLET2KSystgRcOallocatorlEpairlEconstsPt2krewcLcLET2KSystcOt2krewcLcLT2KSystInfomUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,T2KWghtEngineI*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOt2krewcLcLT2KWghtEngineImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOt2krewcLcLT2KWghtEngineImUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,t2krew::T2KWghtEngineI*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOt2krewcLcLT2KWghtEngineImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOt2krewcLcLT2KWghtEngineImUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,t2krew::T2KWghtEngineI*,less<string> >",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOt2krewcLcLT2KWghtEngineImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOt2krewcLcLT2KWghtEngineImUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<neut::rew::NSyst_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEneutcLcLrewcLcLENSystcOallocatorlEneutcLcLrewcLcLENSystgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEneutcLcLrewcLcLENSystcOallocatorlEneutcLcLrewcLcLENSystgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEneutcLcLrewcLcLENSystcOallocatorlEneutcLcLrewcLcLENSystgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEneutcLcLrewcLcLENSystcOallocatorlEneutcLcLrewcLcLENSystgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEneutcLcLrewcLcLENSystcOallocatorlEneutcLcLrewcLcLENSystgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<neut::rew::ENSyst>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEneutcLcLrewcLcLENSystcOallocatorlEneutcLcLrewcLcLENSystgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<NSyst_t,NSystInfo*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEneutcLcLrewcLcLENSystcOneutcLcLrewcLcLNSystInfomUcOlesslEneutcLcLrewcLcLENSystgRcOallocatorlEpairlEconstsPneutcLcLrewcLcLENSystcOneutcLcLrewcLcLNSystInfomUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<neut::rew::ENSyst,neut::rew::NSystInfo*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEneutcLcLrewcLcLENSystcOneutcLcLrewcLcLNSystInfomUcOlesslEneutcLcLrewcLcLENSystgRcOallocatorlEpairlEconstsPneutcLcLrewcLcLENSystcOneutcLcLrewcLcLNSystInfomUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<neut::rew::ENSyst,neut::rew::NSystInfo*,less<neut::rew::ENSyst> >",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEneutcLcLrewcLcLENSystcOneutcLcLrewcLcLNSystInfomUcOlesslEneutcLcLrewcLcLENSystgRcOallocatorlEpairlEconstsPneutcLcLrewcLcLENSystcOneutcLcLrewcLcLNSystInfomUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,NReWeightI*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOneutcLcLrewcLcLNReWeightImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOneutcLcLrewcLcLNReWeightImUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,neut::rew::NReWeightI*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOneutcLcLrewcLcLNReWeightImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOneutcLcLrewcLcLNReWeightImUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,neut::rew::NReWeightI*,less<string> >",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOneutcLcLrewcLcLNReWeightImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOneutcLcLrewcLcLNReWeightImUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<niwg::rew::NIWGSyst_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEniwgcLcLrewcLcLENIWGSystcOallocatorlEniwgcLcLrewcLcLENIWGSystgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEniwgcLcLrewcLcLENIWGSystcOallocatorlEniwgcLcLrewcLcLENIWGSystgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEniwgcLcLrewcLcLENIWGSystcOallocatorlEniwgcLcLrewcLcLENIWGSystgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEniwgcLcLrewcLcLENIWGSystcOallocatorlEniwgcLcLrewcLcLENIWGSystgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEniwgcLcLrewcLcLENIWGSystcOallocatorlEniwgcLcLrewcLcLENIWGSystgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<niwg::rew::ENIWGSyst>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEniwgcLcLrewcLcLENIWGSystcOallocatorlEniwgcLcLrewcLcLENIWGSystgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<NIWGSyst_t,NIWGSystInfo*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEniwgcLcLrewcLcLENIWGSystcOniwgcLcLrewcLcLNIWGSystInfomUcOlesslEniwgcLcLrewcLcLENIWGSystgRcOallocatorlEpairlEconstsPniwgcLcLrewcLcLENIWGSystcOniwgcLcLrewcLcLNIWGSystInfomUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<niwg::rew::ENIWGSyst,niwg::rew::NIWGSystInfo*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEniwgcLcLrewcLcLENIWGSystcOniwgcLcLrewcLcLNIWGSystInfomUcOlesslEniwgcLcLrewcLcLENIWGSystgRcOallocatorlEpairlEconstsPniwgcLcLrewcLcLENIWGSystcOniwgcLcLrewcLcLNIWGSystInfomUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<niwg::rew::ENIWGSyst,niwg::rew::NIWGSystInfo*,less<niwg::rew::ENIWGSyst> >",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEniwgcLcLrewcLcLENIWGSystcOniwgcLcLrewcLcLNIWGSystInfomUcOlesslEniwgcLcLrewcLcLENIWGSystgRcOallocatorlEpairlEconstsPniwgcLcLrewcLcLENIWGSystcOniwgcLcLrewcLcLNIWGSystInfomUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<NIWGPartStack>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEniwgcLcLrewcLcLNIWGPartStackcOallocatorlEniwgcLcLrewcLcLNIWGPartStackgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEniwgcLcLrewcLcLNIWGPartStackcOallocatorlEniwgcLcLrewcLcLNIWGPartStackgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEniwgcLcLrewcLcLNIWGPartStackcOallocatorlEniwgcLcLrewcLcLNIWGPartStackgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEniwgcLcLrewcLcLNIWGPartStackcOallocatorlEniwgcLcLrewcLcLNIWGPartStackgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEniwgcLcLrewcLcLNIWGPartStackcOallocatorlEniwgcLcLrewcLcLNIWGPartStackgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<niwg::rew::NIWGPartStack>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEniwgcLcLrewcLcLNIWGPartStackcOallocatorlEniwgcLcLrewcLcLNIWGPartStackgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,NIWGReWeightI*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOniwgcLcLrewcLcLNIWGReWeightImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOniwgcLcLrewcLcLNIWGReWeightImUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,niwg::rew::NIWGReWeightI*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOniwgcLcLrewcLcLNIWGReWeightImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOniwgcLcLrewcLcLNIWGReWeightImUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,niwg::rew::NIWGReWeightI*,less<string> >",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOniwgcLcLrewcLcLNIWGReWeightImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOniwgcLcLrewcLcLNIWGReWeightImUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TH2D*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOTH2DmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH2DmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TH2D*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOTH2DmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH2DmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TH2D*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOTH2DmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH2DmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TH2D*,less<string> >",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOTH2DmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH2DmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::pair<int,int>,TH3D*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEpairlEintcOintgRcOTH3DmUcOlesslEpairlEintcOintgRsPgRcOallocatorlEpairlEconstsPpairlEintcOintgRcOTH3DmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<pair<int,int>,TH3D*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEpairlEintcOintgRcOTH3DmUcOlesslEpairlEintcOintgRsPgRcOallocatorlEpairlEconstsPpairlEintcOintgRcOTH3DmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<pair<int,int>,TH3D*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEpairlEintcOintgRcOTH3DmUcOlesslEpairlEintcOintgRsPgRcOallocatorlEpairlEconstsPpairlEintcOintgRcOTH3DmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<pair<int,int>,TH3D*,less<pair<int,int> > >",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEpairlEintcOintgRcOTH3DmUcOlesslEpairlEintcOintgRsPgRcOallocatorlEpairlEconstsPpairlEintcOintgRcOTH3DmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TH3D*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEintcOTH3DmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTH3DmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TH3D*,less<int> >",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEintcOTH3DmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTH3DmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TH1D*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEintcOTH1DmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTH1DmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TH1D*,less<int> >",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEintcOTH1DmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTH1DmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::vector<double> >",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double> >",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double,allocator<double> > >",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("list<FitSpline*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_listlEFitSplinemUcOallocatorlEFitSplinemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TF1>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETF1cOallocatorlETF1gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlETF1cOallocatorlETF1gRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETF1cOallocatorlETF1gRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlETF1cOallocatorlETF1gRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETF1cOallocatorlETF1gRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<FitEventBase*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEFitEventBasemUcOallocatorlEFitEventBasemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEFitEventBasemUcOallocatorlEFitEventBasemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEFitEventBasemUcOallocatorlEFitEventBasemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEFitEventBasemUcOallocatorlEFitEventBasemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEFitEventBasemUcOallocatorlEFitEventBasemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH1D*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH1*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlETH1mUcOallocatorlETH1mUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlETH1mUcOallocatorlETH1mUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */
extern "C" void G__cpp_setup_memvar_ROOT_DICT_ExternalDataFit_ANL() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/

/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfunc_ROOT_DICT_ExternalDataFit_ANL() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {
}

static void G__cpp_setup_global8() {
}

static void G__cpp_setup_global9() {
}

static void G__cpp_setup_global10() {
}

static void G__cpp_setup_global11() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_global_ROOT_DICT_ExternalDataFit_ANL() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
  G__cpp_setup_global8();
  G__cpp_setup_global9();
  G__cpp_setup_global10();
  G__cpp_setup_global11();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {
}

static void G__cpp_setup_func30() {
}

static void G__cpp_setup_func31() {
}

static void G__cpp_setup_func32() {
}

static void G__cpp_setup_func33() {
}

static void G__cpp_setup_func34() {
}

static void G__cpp_setup_func35() {
}

static void G__cpp_setup_func36() {
}

static void G__cpp_setup_func37() {
}

static void G__cpp_setup_func38() {
}

static void G__cpp_setup_func39() {
}

static void G__cpp_setup_func40() {
}

static void G__cpp_setup_func41() {
}

static void G__cpp_setup_func42() {
}

static void G__cpp_setup_func43() {
}

static void G__cpp_setup_func44() {
}

static void G__cpp_setup_func45() {
}

static void G__cpp_setup_func46() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_func_ROOT_DICT_ExternalDataFit_ANL() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
  G__cpp_setup_func30();
  G__cpp_setup_func31();
  G__cpp_setup_func32();
  G__cpp_setup_func33();
  G__cpp_setup_func34();
  G__cpp_setup_func35();
  G__cpp_setup_func36();
  G__cpp_setup_func37();
  G__cpp_setup_func38();
  G__cpp_setup_func39();
  G__cpp_setup_func40();
  G__cpp_setup_func41();
  G__cpp_setup_func42();
  G__cpp_setup_func43();
  G__cpp_setup_func44();
  G__cpp_setup_func45();
  G__cpp_setup_func46();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TElementActionTlEdoublegR = { "TElementActionT<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TElementPosActionTlEdoublegR = { "TElementPosActionT<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSymlEdoublegR = { "TMatrixTSym<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTlEdoublegR = { "TMatrixT<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTRow_constlEdoublegR = { "TMatrixTRow_const<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTRowlEdoublegR = { "TMatrixTRow<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTColumn_constlEdoublegR = { "TMatrixTColumn_const<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTDiag_constlEdoublegR = { "TMatrixTDiag_const<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTFlat_constlEdoublegR = { "TMatrixTFlat_const<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSub_constlEdoublegR = { "TMatrixTSub_const<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseRow_constlEdoublegR = { "TMatrixTSparseRow_const<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparselEdoublegR = { "TMatrixTSparse<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseDiag_constlEdoublegR = { "TMatrixTSparseDiag_const<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTColumnlEdoublegR = { "TMatrixTColumn<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTDiaglEdoublegR = { "TMatrixTDiag<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTFlatlEdoublegR = { "TMatrixTFlat<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSublEdoublegR = { "TMatrixTSub<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseRowlEdoublegR = { "TMatrixTSparseRow<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseDiaglEdoublegR = { "TMatrixTSparseDiag<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEFitParticlecOallocatorlEFitParticlegRsPgR = { "vector<FitParticle,allocator<FitParticle> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEFitParticlecOallocatorlEFitParticlegRsPgRcLcLiteratorgR = { "reverse_iterator<vector<FitParticle,allocator<FitParticle> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR = { "map<string,int,less<string>,allocator<pair<const string,int> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR = { "map<string,double,less<string>,allocator<pair<const string,double> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR = { "map<string,string,less<string>,allocator<pair<const string,string> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR = { "map<string,bool,less<string>,allocator<pair<const string,bool> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEt2krewcLcLET2KSystcOallocatorlEt2krewcLcLET2KSystgRsPgR = { "vector<t2krew::ET2KSyst,allocator<t2krew::ET2KSyst> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEt2krewcLcLET2KSystcOallocatorlEt2krewcLcLET2KSystgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<t2krew::ET2KSyst,allocator<t2krew::ET2KSyst> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_maplEt2krewcLcLET2KSystcOt2krewcLcLT2KSystInfomUcOlesslEt2krewcLcLET2KSystgRcOallocatorlEpairlEconstsPt2krewcLcLET2KSystcOt2krewcLcLT2KSystInfomUgRsPgRsPgR = { "map<t2krew::ET2KSyst,t2krew::T2KSystInfo*,less<t2krew::ET2KSyst>,allocator<pair<const t2krew::ET2KSyst,t2krew::T2KSystInfo*> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOt2krewcLcLT2KWghtEngineImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOt2krewcLcLT2KWghtEngineImUgRsPgRsPgR = { "map<string,t2krew::T2KWghtEngineI*,less<string>,allocator<pair<const string,t2krew::T2KWghtEngineI*> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEneutcLcLrewcLcLENSystcOallocatorlEneutcLcLrewcLcLENSystgRsPgR = { "vector<neut::rew::ENSyst,allocator<neut::rew::ENSyst> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEneutcLcLrewcLcLENSystcOallocatorlEneutcLcLrewcLcLENSystgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<neut::rew::ENSyst,allocator<neut::rew::ENSyst> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_maplEneutcLcLrewcLcLENSystcOneutcLcLrewcLcLNSystInfomUcOlesslEneutcLcLrewcLcLENSystgRcOallocatorlEpairlEconstsPneutcLcLrewcLcLENSystcOneutcLcLrewcLcLNSystInfomUgRsPgRsPgR = { "map<neut::rew::ENSyst,neut::rew::NSystInfo*,less<neut::rew::ENSyst>,allocator<pair<const neut::rew::ENSyst,neut::rew::NSystInfo*> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOneutcLcLrewcLcLNReWeightImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOneutcLcLrewcLcLNReWeightImUgRsPgRsPgR = { "map<string,neut::rew::NReWeightI*,less<string>,allocator<pair<const string,neut::rew::NReWeightI*> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEniwgcLcLrewcLcLENIWGSystcOallocatorlEniwgcLcLrewcLcLENIWGSystgRsPgR = { "vector<niwg::rew::ENIWGSyst,allocator<niwg::rew::ENIWGSyst> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEniwgcLcLrewcLcLENIWGSystcOallocatorlEniwgcLcLrewcLcLENIWGSystgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<niwg::rew::ENIWGSyst,allocator<niwg::rew::ENIWGSyst> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_maplEniwgcLcLrewcLcLENIWGSystcOniwgcLcLrewcLcLNIWGSystInfomUcOlesslEniwgcLcLrewcLcLENIWGSystgRcOallocatorlEpairlEconstsPniwgcLcLrewcLcLENIWGSystcOniwgcLcLrewcLcLNIWGSystInfomUgRsPgRsPgR = { "map<niwg::rew::ENIWGSyst,niwg::rew::NIWGSystInfo*,less<niwg::rew::ENIWGSyst>,allocator<pair<const niwg::rew::ENIWGSyst,niwg::rew::NIWGSystInfo*> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEniwgcLcLrewcLcLNIWGPartStackcOallocatorlEniwgcLcLrewcLcLNIWGPartStackgRsPgR = { "vector<niwg::rew::NIWGPartStack,allocator<niwg::rew::NIWGPartStack> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEniwgcLcLrewcLcLNIWGPartStackcOallocatorlEniwgcLcLrewcLcLNIWGPartStackgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<niwg::rew::NIWGPartStack,allocator<niwg::rew::NIWGPartStack> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOniwgcLcLrewcLcLNIWGReWeightImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOniwgcLcLrewcLcLNIWGReWeightImUgRsPgRsPgR = { "map<string,niwg::rew::NIWGReWeightI*,less<string>,allocator<pair<const string,niwg::rew::NIWGReWeightI*> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOTH2DmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH2DmUgRsPgRsPgR = { "map<string,TH2D*,less<string>,allocator<pair<const string,TH2D*> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_maplEpairlEintcOintgRcOTH3DmUcOlesslEpairlEintcOintgRsPgRcOallocatorlEpairlEconstsPpairlEintcOintgRcOTH3DmUgRsPgRsPgR = { "map<pair<int,int>,TH3D*,less<pair<int,int> >,allocator<pair<const pair<int,int>,TH3D*> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_maplEintcOTH3DmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTH3DmUgRsPgRsPgR = { "map<int,TH3D*,less<int>,allocator<pair<const int,TH3D*> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_maplEintcOTH1DmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTH1DmUgRsPgRsPgR = { "map<int,TH1D*,less<int>,allocator<pair<const int,TH1D*> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR = { "vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_listlEFitSplinemUcOallocatorlEFitSplinemUgRsPgR = { "list<FitSpline*,allocator<FitSpline*> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETF1cOallocatorlETF1gRsPgR = { "vector<TF1,allocator<TF1> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlETF1cOallocatorlETF1gRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TF1,allocator<TF1> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEFitEventBasemUcOallocatorlEFitEventBasemUgRsPgR = { "vector<FitEventBase*,allocator<FitEventBase*> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEFitEventBasemUcOallocatorlEFitEventBasemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<FitEventBase*,allocator<FitEventBase*> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR = { "vector<TH1D*,allocator<TH1D*> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH1D*,allocator<TH1D*> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR = { "vector<TH1*,allocator<TH1*> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlETH1mUcOallocatorlETH1mUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH1*,allocator<TH1*> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtable_ROOT_DICT_ExternalDataFit_ANL() {
  G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TVectorTlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TVectorTlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TElementActionTlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TElementPosActionTlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSymlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTRow_constlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTRowlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTColumn_constlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTDiag_constlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTFlat_constlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSub_constlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseRow_constlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparselEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseDiag_constlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTColumnlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTDiaglEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTFlatlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSublEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseRowlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseDiaglEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEFitParticlecOallocatorlEFitParticlegRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEFitParticlecOallocatorlEFitParticlegRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEt2krewcLcLET2KSystcOallocatorlEt2krewcLcLET2KSystgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEt2krewcLcLET2KSystcOallocatorlEt2krewcLcLET2KSystgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_maplEt2krewcLcLET2KSystcOt2krewcLcLT2KSystInfomUcOlesslEt2krewcLcLET2KSystgRcOallocatorlEpairlEconstsPt2krewcLcLET2KSystcOt2krewcLcLT2KSystInfomUgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOt2krewcLcLT2KWghtEngineImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOt2krewcLcLT2KWghtEngineImUgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEneutcLcLrewcLcLENSystcOallocatorlEneutcLcLrewcLcLENSystgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEneutcLcLrewcLcLENSystcOallocatorlEneutcLcLrewcLcLENSystgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_maplEneutcLcLrewcLcLENSystcOneutcLcLrewcLcLNSystInfomUcOlesslEneutcLcLrewcLcLENSystgRcOallocatorlEpairlEconstsPneutcLcLrewcLcLENSystcOneutcLcLrewcLcLNSystInfomUgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOneutcLcLrewcLcLNReWeightImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOneutcLcLrewcLcLNReWeightImUgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEniwgcLcLrewcLcLENIWGSystcOallocatorlEniwgcLcLrewcLcLENIWGSystgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEniwgcLcLrewcLcLENIWGSystcOallocatorlEniwgcLcLrewcLcLENIWGSystgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_maplEniwgcLcLrewcLcLENIWGSystcOniwgcLcLrewcLcLNIWGSystInfomUcOlesslEniwgcLcLrewcLcLENIWGSystgRcOallocatorlEpairlEconstsPniwgcLcLrewcLcLENIWGSystcOniwgcLcLrewcLcLNIWGSystInfomUgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEniwgcLcLrewcLcLNIWGPartStackcOallocatorlEniwgcLcLrewcLcLNIWGPartStackgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEniwgcLcLrewcLcLNIWGPartStackcOallocatorlEniwgcLcLrewcLcLNIWGPartStackgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOniwgcLcLrewcLcLNIWGReWeightImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOniwgcLcLrewcLcLNIWGReWeightImUgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOTH2DmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH2DmUgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_maplEpairlEintcOintgRcOTH3DmUcOlesslEpairlEintcOintgRsPgRcOallocatorlEpairlEconstsPpairlEintcOintgRcOTH3DmUgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_maplEintcOTH3DmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTH3DmUgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_maplEintcOTH1DmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTH1DmUgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_listlEFitSplinemUcOallocatorlEFitSplinemUgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETF1cOallocatorlETF1gRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlETF1cOallocatorlETF1gRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEFitEventBasemUcOallocatorlEFitEventBasemUgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEFitEventBasemUcOallocatorlEFitEventBasemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlETH1mUcOallocatorlETH1mUgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtable_ROOT_DICT_ExternalDataFit_ANL() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TElementActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TElementPosActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSymlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTColumn_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTFlat_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSub_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparselEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTColumnlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTFlatlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSublEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEFitParticlecOallocatorlEFitParticlegRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEFitParticlecOallocatorlEFitParticlegRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEt2krewcLcLET2KSystcOallocatorlEt2krewcLcLET2KSystgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEt2krewcLcLET2KSystcOallocatorlEt2krewcLcLET2KSystgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEt2krewcLcLET2KSystcOt2krewcLcLT2KSystInfomUcOlesslEt2krewcLcLET2KSystgRcOallocatorlEpairlEconstsPt2krewcLcLET2KSystcOt2krewcLcLT2KSystInfomUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOt2krewcLcLT2KWghtEngineImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOt2krewcLcLT2KWghtEngineImUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEneutcLcLrewcLcLENSystcOallocatorlEneutcLcLrewcLcLENSystgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEneutcLcLrewcLcLENSystcOallocatorlEneutcLcLrewcLcLENSystgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEneutcLcLrewcLcLENSystcOneutcLcLrewcLcLNSystInfomUcOlesslEneutcLcLrewcLcLENSystgRcOallocatorlEpairlEconstsPneutcLcLrewcLcLENSystcOneutcLcLrewcLcLNSystInfomUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOneutcLcLrewcLcLNReWeightImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOneutcLcLrewcLcLNReWeightImUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEniwgcLcLrewcLcLENIWGSystcOallocatorlEniwgcLcLrewcLcLENIWGSystgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEniwgcLcLrewcLcLENIWGSystcOallocatorlEniwgcLcLrewcLcLENIWGSystgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEniwgcLcLrewcLcLENIWGSystcOniwgcLcLrewcLcLNIWGSystInfomUcOlesslEniwgcLcLrewcLcLENIWGSystgRcOallocatorlEpairlEconstsPniwgcLcLrewcLcLENIWGSystcOniwgcLcLrewcLcLNIWGSystInfomUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEniwgcLcLrewcLcLNIWGPartStackcOallocatorlEniwgcLcLrewcLcLNIWGPartStackgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEniwgcLcLrewcLcLNIWGPartStackcOallocatorlEniwgcLcLrewcLcLNIWGPartStackgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOniwgcLcLrewcLcLNIWGReWeightImUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOniwgcLcLrewcLcLNIWGReWeightImUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEstringcOTH2DmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH2DmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEpairlEintcOintgRcOTH3DmUcOlesslEpairlEintcOintgRsPgRcOallocatorlEpairlEconstsPpairlEintcOintgRcOTH3DmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEintcOTH3DmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTH3DmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_maplEintcOTH1DmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTH1DmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_listlEFitSplinemUcOallocatorlEFitSplinemUgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETF1cOallocatorlETF1gRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlETF1cOallocatorlETF1gRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlEFitEventBasemUcOallocatorlEFitEventBasemUgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlEFitEventBasemUcOallocatorlEFitEventBasemUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_ANLLN_reverse_iteratorlEvectorlETH1mUcOallocatorlETH1mUgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setup_ROOT_DICT_ExternalDataFit_ANL(void) {
  G__check_setup_version(30051515,"G__cpp_setup_ROOT_DICT_ExternalDataFit_ANL()");
  G__set_cpp_environment_ROOT_DICT_ExternalDataFit_ANL();
  G__cpp_setup_tagtable_ROOT_DICT_ExternalDataFit_ANL();

  G__cpp_setup_inheritance_ROOT_DICT_ExternalDataFit_ANL();

  G__cpp_setup_typetable_ROOT_DICT_ExternalDataFit_ANL();

  G__cpp_setup_memvar_ROOT_DICT_ExternalDataFit_ANL();

  G__cpp_setup_memfunc_ROOT_DICT_ExternalDataFit_ANL();
  G__cpp_setup_global_ROOT_DICT_ExternalDataFit_ANL();
  G__cpp_setup_func_ROOT_DICT_ExternalDataFit_ANL();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfunc_ROOT_DICT_ExternalDataFit_ANL();
  return;
}
class G__cpp_setup_init_ROOT_DICT_ExternalDataFit_ANL {
  public:
    G__cpp_setup_init_ROOT_DICT_ExternalDataFit_ANL() { G__add_setup_func("_ROOT_DICT_ExternalDataFit_ANL",(G__incsetup)(&G__cpp_setup_ROOT_DICT_ExternalDataFit_ANL)); G__call_setup_funcs(); }
   ~G__cpp_setup_init_ROOT_DICT_ExternalDataFit_ANL() { G__remove_setup_func("_ROOT_DICT_ExternalDataFit_ANL"); }
};
G__cpp_setup_init_ROOT_DICT_ExternalDataFit_ANL G__cpp_setup_initializer_ROOT_DICT_ExternalDataFit_ANL;

