#!/bin/bash

COMMAND_FQP=${0}
COMMAND=$(basename ${COMMAND_FQP})
NUIS_BREADCRUMBS=${COMMAND}

if [ ! -z ${NUIS_CLID_DEBUG} ]; then
echo "[CLI DEBUG](BrCr: ${NUIS_BREADCRUMBS}): ${COMMAND} Arguments(${#}):" "${@}"
fi

if [ -z ${NUISANCE} ]; then
  echo "[ERROR]: We need to be in a NUISANCE environment (\$NUISANCE should be set)."
  exit 1
fi

function nuis_help {
  echo -e "\t ${NUIS_BREADCRUMBS} [global options] <verb> <verb-specific options>"
  echo -e "\tImplemented verbs:"
  echo -e "\t  gen         : Event generation helper"
  echo -e "\t  prep        : Ensure input files contain neccessary information"
  echo -e "\t  flux        : Experimental flux descriptor"
  echo -e "\t  comp        : Make generator--data comparisons"
  echo -e "\t  config      : Check NUISANCE build options"
  echo -e "\t  plot        : Plot the output of nuis comp"
  echo -e "\tGlobal options:"
  echo -e "\t  --debug     : Enable debugging options where implemented"  
  echo -e "Try ${NUIS_BREADCRUMBS} <verb> help for further help for a specific verb."
}

if [ "${1}" == "help" ]; then
  nuis_help
  exit 0
fi

if [ "${1}" == "--debug" ]; then
  echo "[INFO]: Enabling debugging"
  export NUIS_DEBUG=ON
  shift
fi

if [ "${#}" -lt 1 ]; then
  echo -e "[ERROR]: Expected to be passed a sub-command verb like:"
  nuis_help
  exit 1
fi

VERB=${1}
shift

if ! hash ${COMMAND}-${VERB}; then
  echo "[ERROR]: Unknown verb: ${VERB}, could not find `${COMMAND}-${VERB}`."
  exit 1
fi

NUIS_BREADCRUMBS="${NUIS_BREADCRUMBS} ${VERB}" ${COMMAND}-${VERB} "${@}"