#!/bin/bash

COMMAND_FQP=${0}
COMMAND=$(basename ${COMMAND_FQP})

if [ ! -z ${NUIS_CLID_DEBUG} ]; then
  echo "[CLI DEBUG](BrCr: ${NUIS_BREADCRUMBS}): ${COMMAND} Arguments(${#}):" "${@}"
fi

DO_COLLATE=FALSE

I=${#}
while [ ${I} -gt 0 ]; do

  key="${!I}"
  case $key in

  collate)
    DO_COLLATE=TRUE
    ;;

  help)
      nuisplot --help
      exit 0
      ;;

  *)
    SAMPLES+=("${key}")
    ;;
  esac

  I=$((I-1))
done

if [ "${DO_COLLATE}" == "TRUE" ]; then

shift;

function nuis_plot_collate_help {
  echo -e "\tOptions:"
  echo -e "-m|--mc-tag <tag> [<tag2> ...]"
  echo -e "-s|--samples <sname> [<sname2> ...]"
  echo -e "-o|--output <output.tex>"
  echo -e "\thelp                                   : Print this message"
}

MC_TAGS=()
SAMPLES=()
OUTPUTFILE="nuisance_valid.tex"

while [[ ${#} -gt 0 ]]; do

  key="$1"
  case $key in
    -m|--mc-tag)
      
      while [[ ${#} -gt 1 ]] && [ "${2::1}" != "-" ]; do
        MC_TAGS+=("${2}")
        shift
      done 
      ;;

    -s|--sample)
      
      while [[ ${#} -gt 1 ]] && [ "${2::1}" != "-" ]; do
        SAMPLES+=("${2}")
        shift
      done 
      ;;

    -o|--output)
      if [[ ${#} -lt 2 ]]; then
        echo "[ERROR]: ${1} expected a value."
        exit 1
      fi

      OUTPUTFILE="$2"
      shift # past argument
      ;;

    help)
      nuis_plot_collate_help
      exit 0
      ;;
  esac
  shift
done

cat << "EOF" > ${OUTPUTFILE}
\documentclass{article}
\RequirePackage[a4paper, margin=1.5cm]{geometry}
\RequirePackage{graphicx}
\RequirePackage{subfloat}
\RequirePackage{xspace}
\RequirePackage{hyperref}

\title{Some NUISANCE Plots}
\date{}

\begin{document}

\maketitle

EOF

COLS="r|"
HEADERLINE="Samples"

for (( i=0; i<${#MC_TAGS[@]}; ++i )); do 
  COLS="${COLS}|c"
  MC_TAG_HYPHEN=$(echo ${MC_TAGS[${i}]} | sed 's:_:-:g')
  HEADERLINE="${HEADERLINE} & ${MC_TAG_HYPHEN}"
done

cat << EOF >> ${OUTPUTFILE}
\begin{tabular}{${COLS}}
${HEADERLINE}
EOF

echo -n \\ >> ${OUTPUTFILE}
echo \\ \\hline >> ${OUTPUTFILE}

NMCTAGS=${#MC_TAGS[@]}

for SAMPLE in ${SAMPLES[@]}; do
  SAMPLE_HYPHEN=$(echo ${SAMPLE} | sed 's:_:-:g')
  echo -n "\\hyperref[fig:${SAMPLE_HYPHEN}]" >> ${OUTPUTFILE}
  echo "{${SAMPLE}} &" | sed 's:_:\\_:g' >> ${OUTPUTFILE}
  for (( i=0; i<${#MC_TAGS[@]}; ++i )); do
    if [ "${i}" == "$((NMCTAGS-1))" ]; then
      cat ${SAMPLE}_${MC_TAGS[${i}]}.chi2 >> ${OUTPUTFILE}
      #this is the only way I could get a double bslash
      echo -n \\ >> ${OUTPUTFILE}
      echo \\ >> ${OUTPUTFILE}
    else
      cat ${SAMPLE}_${MC_TAGS[${i}]}.chi2 >> ${OUTPUTFILE}
      echo "&" >> ${OUTPUTFILE}
    fi
  done
done

cat << EOF >> ${OUTPUTFILE}
\end{tabular}
\pagebreak
EOF

for SAMPLE in ${SAMPLES[@]}; do
  SAMPLE_HYPHEN=$(echo ${SAMPLE} | sed 's:_:-:g')
  echo "\\begin{figure}" >> ${OUTPUTFILE}
  echo "\\centering" >> ${OUTPUTFILE}
  echo "\\includegraphics{${SAMPLE}}" >> ${OUTPUTFILE}
  echo "\\label{fig:${SAMPLE_HYPHEN}}" >> ${OUTPUTFILE}
  echo "\\caption{${SAMPLE_HYPHEN}}" >> ${OUTPUTFILE}
  echo "\\end{figure}" >> ${OUTPUTFILE}
  echo "\\clearpage" >> ${OUTPUTFILE}
done

cat << EOF >> ${OUTPUTFILE}
\end{document}
EOF

else
  nuisplot "${@}"
fi