#!/bin/bash

COMMAND_FQP=${0}
COMMAND=$(basename ${COMMAND_FQP})

if [ ! -z ${NUIS_CLID_DEBUG} ]; then
  echo "[CLI DEBUG](BrCr: ${NUIS_BREADCRUMBS}): ${COMMAND} Arguments(${#}):" "${@}"
fi

I=${#}
while [ ${I} -gt 0 ]; do

  key="${!I}"
  case $key in

  help)
      PrepareGENIE -h
      exit 0
      ;;
  esac

  I=$((I-1))
done

PrepareGENIE "${@}"