#!/bin/bash

COMMAND_FQP=${0}
COMMAND=$(basename ${COMMAND_FQP})

if [ ! -z ${NUIS_CLID_DEBUG} ]; then
echo "[CLI DEBUG](BrCr: ${NUIS_BREADCRUMBS}): ${COMMAND} Arguments(${#}): ${@}"
fi

if [ "${#}" -lt 1 ]; then
  echo -e "[ERROR]: Expected to be passed a sub command verb like:"
  echo -e "\t ${COMMAND} <verb> <verb-specific options>"
  echo -e "Implemented verbs:"

  if nuis config GENIE_ENABLED; then
    echo -e "\tGENIE       -- Event generation helper"
  fi
  if nuis config GENIE_ENABLED; then
    echo -e "\tNEUT        -- Experimental flux descriptor"
  fi
  if nuis config NuWro_ENABLED; then
    echo -e "\tNuWro       -- Experimental flux descriptor"
  fi
  if hash GiBUU.x &> /dev/null; then
    echo -e "\tGiBUU       -- Experimental flux descriptor"
  fi

  echo -e "Try ${COMMAND} <verb> help for further help for a specific verb."
  exit 1
fi

VERB=${1}
shift

if ! hash ${COMMAND}-${VERB}; then
  echo "[ERROR]: Unknown verb: ${VERB}, could not find `${COMMAND}-${VERB}`."
  exit 1
fi

NUIS_BREADCRUMBS="${NUIS_BREADCRUMBS} ${VERB}" ${COMMAND}-${VERB} ${@}