// Copyright 2016 L. Pickering, P Stowell, R. Terri, C. Wilkinson, C. Wret

/*******************************************************************************
*    This file is part of NuFiX.
*
*    NuFiX is free software: you can redistribute it and/or modify
*    it under the terms of the GNU General Public License as published by
*    the Free Software Foundation, either version 3 of the License, or
*    (at your option) any later version.
*
*    NuFiX is distributed in the hope that it will be useful,
*    but WITHOUT ANY WARRANTY; without even the implied warranty of
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*    GNU General Public License for more details.
*
*    You should have received a copy of the GNU General Public License
*    along with NuFiX.  If not, see <http://www.gnu.org/licenses/>.
*******************************************************************************/

/********************************************************************
* /home/stowell/t2krep/NIWG/externalDataFitter/head/src/FitUtils/_ROOT_DICT_ExternalDataFit_FitUtils.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/stowell/t2krep/NIWG/externalDataFitter/head/src/FitUtils/_ROOT_DICT_ExternalDataFit_FitUtils.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtable_ROOT_DICT_ExternalDataFit_FitUtils();
extern void G__cpp_setup_inheritance_ROOT_DICT_ExternalDataFit_FitUtils();
extern void G__cpp_setup_typetable_ROOT_DICT_ExternalDataFit_FitUtils();
extern void G__cpp_setup_memvar_ROOT_DICT_ExternalDataFit_FitUtils();
extern void G__cpp_setup_global_ROOT_DICT_ExternalDataFit_FitUtils();
extern void G__cpp_setup_memfunc_ROOT_DICT_ExternalDataFit_FitUtils();
extern void G__cpp_setup_func_ROOT_DICT_ExternalDataFit_FitUtils();
extern void G__set_cpp_environment_ROOT_DICT_ExternalDataFit_FitUtils();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "FitUtils.h"
