// Copyright 2016 L. Pickering, P Stowell, R. Terri, C. Wilkinson, C. Wret

/*******************************************************************************
*    This file is part of NuFiX.
*
*    NuFiX is free software: you can redistribute it and/or modify
*    it under the terms of the GNU General Public License as published by
*    the Free Software Foundation, either version 3 of the License, or
*    (at your option) any later version.
*
*    NuFiX is distributed in the hope that it will be useful,
*    but WITHOUT ANY WARRANTY; without even the implied warranty of
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*    GNU General Public License for more details.
*
*    You should have received a copy of the GNU General Public License
*    along with NuFiX.  If not, see <http://www.gnu.org/licenses/>.
*******************************************************************************/

/********************************************************************
* /home/stowell/t2krep/NIWG/externalDataFitter/head/src/Stats/_ROOT_DICT_ExternalDataFit_Stats.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/stowell/t2krep/NIWG/externalDataFitter/head/src/Stats/_ROOT_DICT_ExternalDataFit_Stats.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtable_ROOT_DICT_ExternalDataFit_Stats();
extern void G__cpp_setup_inheritance_ROOT_DICT_ExternalDataFit_Stats();
extern void G__cpp_setup_typetable_ROOT_DICT_ExternalDataFit_Stats();
extern void G__cpp_setup_memvar_ROOT_DICT_ExternalDataFit_Stats();
extern void G__cpp_setup_global_ROOT_DICT_ExternalDataFit_Stats();
extern void G__cpp_setup_memfunc_ROOT_DICT_ExternalDataFit_Stats();
extern void G__cpp_setup_func_ROOT_DICT_ExternalDataFit_Stats();
extern void G__set_cpp_environment_ROOT_DICT_ExternalDataFit_Stats();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "FitStatistics1D.h"
#include "FitStatistics2D.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TVectorTlEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TVectorTlEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSparselEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSparseDiaglEdoublegR;

/* STUB derived class for protected member access */
