//
// File generated by rootcint at Wed Feb 17 02:49:35 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dIhomedIstowelldIt2krepdINIWGdIexternalDataFitterdIheaddIsrcdIStatsdI_ROOT_DICT_ExternalDataFit_Stats
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "_ROOT_DICT_ExternalDataFit_Stats.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

/********************************************************
* /home/stowell/t2krep/NIWG/externalDataFitter/head/src/Stats/_ROOT_DICT_ExternalDataFit_Stats.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtable_ROOT_DICT_ExternalDataFit_Stats();

extern "C" void G__set_cpp_environment_ROOT_DICT_ExternalDataFit_Stats() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("FitStatistics1D.h");
  G__add_compiledheader("FitStatistics2D.h");
  G__cpp_reset_tagtable_ROOT_DICT_ExternalDataFit_Stats();
}
#include <new>
extern "C" int G__cpp_dllrev_ROOT_DICT_ExternalDataFit_Stats() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfunc_ROOT_DICT_ExternalDataFit_Stats {
 public:
  G__Sizep2memfunc_ROOT_DICT_ExternalDataFit_Stats(): p(&G__Sizep2memfunc_ROOT_DICT_ExternalDataFit_Stats::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfunc_ROOT_DICT_ExternalDataFit_Stats::*p)();
};

size_t G__get_sizep2memfunc_ROOT_DICT_ExternalDataFit_Stats()
{
  G__Sizep2memfunc_ROOT_DICT_ExternalDataFit_Stats a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritance_ROOT_DICT_ExternalDataFit_Stats() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetable_ROOT_DICT_ExternalDataFit_Stats() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSym<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSymlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTColumn_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTFlat_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSub_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSparseRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSparseDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTColumnlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTFlatlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSublEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSparseRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSparseDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_TElementActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_TElementPosActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparse<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSparselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */
extern "C" void G__cpp_setup_memvar_ROOT_DICT_ExternalDataFit_Stats() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/

/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfunc_ROOT_DICT_ExternalDataFit_Stats() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_global_ROOT_DICT_ExternalDataFit_Stats() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_func_ROOT_DICT_ExternalDataFit_Stats() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TElementActionTlEdoublegR = { "TElementActionT<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TElementPosActionTlEdoublegR = { "TElementPosActionT<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSymlEdoublegR = { "TMatrixTSym<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTlEdoublegR = { "TMatrixT<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTRow_constlEdoublegR = { "TMatrixTRow_const<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTRowlEdoublegR = { "TMatrixTRow<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTColumn_constlEdoublegR = { "TMatrixTColumn_const<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTDiag_constlEdoublegR = { "TMatrixTDiag_const<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTFlat_constlEdoublegR = { "TMatrixTFlat_const<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSub_constlEdoublegR = { "TMatrixTSub_const<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSparseRow_constlEdoublegR = { "TMatrixTSparseRow_const<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSparselEdoublegR = { "TMatrixTSparse<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSparseDiag_constlEdoublegR = { "TMatrixTSparseDiag_const<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTColumnlEdoublegR = { "TMatrixTColumn<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTDiaglEdoublegR = { "TMatrixTDiag<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTFlatlEdoublegR = { "TMatrixTFlat<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSublEdoublegR = { "TMatrixTSub<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSparseRowlEdoublegR = { "TMatrixTSparseRow<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSparseDiaglEdoublegR = { "TMatrixTSparseDiag<double>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtable_ROOT_DICT_ExternalDataFit_Stats() {
  G___ROOT_DICT_ExternalDataFit_StatsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_StatsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_StatsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_StatsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_StatsLN_TVectorTlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_StatsLN_TVectorTlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_StatsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_StatsLN_TElementActionTlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_StatsLN_TElementPosActionTlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSymlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTRow_constlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTRowlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTColumn_constlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTDiag_constlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTFlat_constlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSub_constlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSparseRow_constlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSparselEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSparseDiag_constlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTColumnlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTDiaglEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTFlatlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSublEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSparseRowlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSparseDiaglEdoublegR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtable_ROOT_DICT_ExternalDataFit_Stats() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_TElementActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_TElementPosActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSymlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTColumn_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTFlat_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSub_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSparseRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSparselEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSparseDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTColumnlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTFlatlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSublEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSparseRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_StatsLN_TMatrixTSparseDiaglEdoublegR);
}
extern "C" void G__cpp_setup_ROOT_DICT_ExternalDataFit_Stats(void) {
  G__check_setup_version(30051515,"G__cpp_setup_ROOT_DICT_ExternalDataFit_Stats()");
  G__set_cpp_environment_ROOT_DICT_ExternalDataFit_Stats();
  G__cpp_setup_tagtable_ROOT_DICT_ExternalDataFit_Stats();

  G__cpp_setup_inheritance_ROOT_DICT_ExternalDataFit_Stats();

  G__cpp_setup_typetable_ROOT_DICT_ExternalDataFit_Stats();

  G__cpp_setup_memvar_ROOT_DICT_ExternalDataFit_Stats();

  G__cpp_setup_memfunc_ROOT_DICT_ExternalDataFit_Stats();
  G__cpp_setup_global_ROOT_DICT_ExternalDataFit_Stats();
  G__cpp_setup_func_ROOT_DICT_ExternalDataFit_Stats();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfunc_ROOT_DICT_ExternalDataFit_Stats();
  return;
}
class G__cpp_setup_init_ROOT_DICT_ExternalDataFit_Stats {
  public:
    G__cpp_setup_init_ROOT_DICT_ExternalDataFit_Stats() { G__add_setup_func("_ROOT_DICT_ExternalDataFit_Stats",(G__incsetup)(&G__cpp_setup_ROOT_DICT_ExternalDataFit_Stats)); G__call_setup_funcs(); }
   ~G__cpp_setup_init_ROOT_DICT_ExternalDataFit_Stats() { G__remove_setup_func("_ROOT_DICT_ExternalDataFit_Stats"); }
};
G__cpp_setup_init_ROOT_DICT_ExternalDataFit_Stats G__cpp_setup_initializer_ROOT_DICT_ExternalDataFit_Stats;

