//
// File generated by rootcint at Fri Jul  8 11:19:28 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dIhomedIstowelldIt2krepdINIWGdIexternalDataFitterdIsrcdIUtilsdI_ROOT_DICT_ExternalDataFit_Utils
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "_ROOT_DICT_ExternalDataFit_Utils.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::FitParameters FitParameters;
      #else
      class FitParameters  {
         public:
         //friend XX;
         // To force the creation of a virtual table, throw just in case.
         virtual ~FitParameters() throw() {};
         string parFileName; //
         map< ::string, ::string > parameterMap_all; //
         int variables; //
         bool nuwro_enabled; //
         ::TFile* out; //pointer to output file
         string outputname; //
         map< ::string, int > parameterMap_int; //
         map< ::string, double > parameterMap_double; //
         map< ::string, ::string > parameterMap_string; //
         map< ::string, bool > parameterMap_bool; //
         vector< ::string > parNames; //
         vector< ::string > parValues; //
         vector< ::string > cardLines; //
         int iteration; //
      };
      #endif

   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace FitPar {
   namespace ROOTDict {
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance();
      static void FitPar_Dictionary();

      // Function generating the singleton type initializer
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance()
      {
         static ::ROOT::TGenericClassInfo 
            instance("FitPar", 0 /*version*/, "./FitParameters.h", 111,
                     ::ROOT::DefineBehavior((void*)0,(void*)0),
                     &FitPar_Dictionary, 0);
         return &instance;
      }
      // Insure that the inline function is _not_ optimized away by the compiler
      ::ROOT::TGenericClassInfo *(*_R__UNIQUE_(InitFunctionKeeper))() = &GenerateInitInstance;  
      // Static variable to force the class initialization
      static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance(); R__UseDummy(_R__UNIQUE_(Init));

      // Dictionary for non-ClassDef classes
      static void FitPar_Dictionary() {
         GenerateInitInstance()->GetClass();
      }

   }
}

namespace ROOTDict {
   void FitParameters_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void FitParameters_Dictionary();
   static void *new_FitParameters(void *p = 0);
   static void *newArray_FitParameters(Long_t size, void *p);
   static void delete_FitParameters(void *p);
   static void deleteArray_FitParameters(void *p);
   static void destruct_FitParameters(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::FitParameters*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::FitParameters) == sizeof( ::ROOTShadow::Shadow::FitParameters));
      ::FitParameters *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::FitParameters),0);
      static ::ROOT::TGenericClassInfo 
         instance("FitParameters", "./FitParameters.h", 48,
                  typeid(::FitParameters), ::ROOT::DefineBehavior(ptr, ptr),
                  &FitParameters_ShowMembers, &FitParameters_Dictionary, isa_proxy, 4,
                  sizeof(::FitParameters) );
      instance.SetNew(&new_FitParameters);
      instance.SetNewArray(&newArray_FitParameters);
      instance.SetDelete(&delete_FitParameters);
      instance.SetDeleteArray(&deleteArray_FitParameters);
      instance.SetDestructor(&destruct_FitParameters);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::FitParameters*)
   {
      return GenerateInitInstanceLocal((::FitParameters*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::FitParameters*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void FitParameters_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::FitParameters*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

//______________________________________________________________________________
namespace ROOTDict {
   void FitParameters_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class FitParameters.
      typedef ::ROOTShadow::Shadow::FitParameters ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOTDict::GenerateInitInstanceLocal((const ::FitParameters*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "parFileName", (void*)&sobj->parFileName);
      R__insp.InspectMember("string", (void*)&sobj->parFileName, "parFileName.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "parameterMap_all", (void*)&sobj->parameterMap_all);
      R__insp.InspectMember("map<std::string,std::string>", (void*)&sobj->parameterMap_all, "parameterMap_all.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "variables", &sobj->variables);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nuwro_enabled", &sobj->nuwro_enabled);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*out", &sobj->out);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "outputname", (void*)&sobj->outputname);
      R__insp.InspectMember("string", (void*)&sobj->outputname, "outputname.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "parameterMap_int", (void*)&sobj->parameterMap_int);
      R__insp.InspectMember("map<std::string,int>", (void*)&sobj->parameterMap_int, "parameterMap_int.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "parameterMap_double", (void*)&sobj->parameterMap_double);
      R__insp.InspectMember("map<std::string,double>", (void*)&sobj->parameterMap_double, "parameterMap_double.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "parameterMap_string", (void*)&sobj->parameterMap_string);
      R__insp.InspectMember("map<std::string,std::string>", (void*)&sobj->parameterMap_string, "parameterMap_string.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "parameterMap_bool", (void*)&sobj->parameterMap_bool);
      R__insp.InspectMember("map<std::string,bool>", (void*)&sobj->parameterMap_bool, "parameterMap_bool.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "parNames", (void*)&sobj->parNames);
      R__insp.InspectMember("vector<std::string>", (void*)&sobj->parNames, "parNames.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "parValues", (void*)&sobj->parValues);
      R__insp.InspectMember("vector<std::string>", (void*)&sobj->parValues, "parValues.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "cardLines", (void*)&sobj->cardLines);
      R__insp.InspectMember("vector<std::string>", (void*)&sobj->cardLines, "cardLines.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "iteration", &sobj->iteration);
   }

}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_FitParameters(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::FitParameters : new ::FitParameters;
   }
   static void *newArray_FitParameters(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::FitParameters[nElements] : new ::FitParameters[nElements];
   }
   // Wrapper around operator delete
   static void delete_FitParameters(void *p) {
      delete ((::FitParameters*)p);
   }
   static void deleteArray_FitParameters(void *p) {
      delete [] ((::FitParameters*)p);
   }
   static void destruct_FitParameters(void *p) {
      typedef ::FitParameters current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::FitParameters

namespace ROOTDict {
   void maplEstringcOboolgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void maplEstringcOboolgR_Dictionary();
   static void *new_maplEstringcOboolgR(void *p = 0);
   static void *newArray_maplEstringcOboolgR(Long_t size, void *p);
   static void delete_maplEstringcOboolgR(void *p);
   static void deleteArray_maplEstringcOboolgR(void *p);
   static void destruct_maplEstringcOboolgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const map<string,bool>*)
   {
      map<string,bool> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,bool>),0);
      static ::ROOT::TGenericClassInfo 
         instance("map<string,bool>", -2, "prec_stl/map", 63,
                  typeid(map<string,bool>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &maplEstringcOboolgR_Dictionary, isa_proxy, 0,
                  sizeof(map<string,bool>) );
      instance.SetNew(&new_maplEstringcOboolgR);
      instance.SetNewArray(&newArray_maplEstringcOboolgR);
      instance.SetDelete(&delete_maplEstringcOboolgR);
      instance.SetDeleteArray(&deleteArray_maplEstringcOboolgR);
      instance.SetDestructor(&destruct_maplEstringcOboolgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::MapInsert< map<string,bool> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const map<string,bool>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void maplEstringcOboolgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const map<string,bool>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_maplEstringcOboolgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,bool> : new map<string,bool>;
   }
   static void *newArray_maplEstringcOboolgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,bool>[nElements] : new map<string,bool>[nElements];
   }
   // Wrapper around operator delete
   static void delete_maplEstringcOboolgR(void *p) {
      delete ((map<string,bool>*)p);
   }
   static void deleteArray_maplEstringcOboolgR(void *p) {
      delete [] ((map<string,bool>*)p);
   }
   static void destruct_maplEstringcOboolgR(void *p) {
      typedef map<string,bool> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class map<string,bool>

namespace ROOTDict {
   void maplEstringcOdoublegR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void maplEstringcOdoublegR_Dictionary();
   static void *new_maplEstringcOdoublegR(void *p = 0);
   static void *newArray_maplEstringcOdoublegR(Long_t size, void *p);
   static void delete_maplEstringcOdoublegR(void *p);
   static void deleteArray_maplEstringcOdoublegR(void *p);
   static void destruct_maplEstringcOdoublegR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const map<string,double>*)
   {
      map<string,double> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,double>),0);
      static ::ROOT::TGenericClassInfo 
         instance("map<string,double>", -2, "map.dll", 0,
                  typeid(map<string,double>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &maplEstringcOdoublegR_Dictionary, isa_proxy, 0,
                  sizeof(map<string,double>) );
      instance.SetNew(&new_maplEstringcOdoublegR);
      instance.SetNewArray(&newArray_maplEstringcOdoublegR);
      instance.SetDelete(&delete_maplEstringcOdoublegR);
      instance.SetDeleteArray(&deleteArray_maplEstringcOdoublegR);
      instance.SetDestructor(&destruct_maplEstringcOdoublegR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::MapInsert< map<string,double> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const map<string,double>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void maplEstringcOdoublegR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const map<string,double>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_maplEstringcOdoublegR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,double> : new map<string,double>;
   }
   static void *newArray_maplEstringcOdoublegR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,double>[nElements] : new map<string,double>[nElements];
   }
   // Wrapper around operator delete
   static void delete_maplEstringcOdoublegR(void *p) {
      delete ((map<string,double>*)p);
   }
   static void deleteArray_maplEstringcOdoublegR(void *p) {
      delete [] ((map<string,double>*)p);
   }
   static void destruct_maplEstringcOdoublegR(void *p) {
      typedef map<string,double> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class map<string,double>

namespace ROOTDict {
   void maplEstringcOintgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void maplEstringcOintgR_Dictionary();
   static void *new_maplEstringcOintgR(void *p = 0);
   static void *newArray_maplEstringcOintgR(Long_t size, void *p);
   static void delete_maplEstringcOintgR(void *p);
   static void deleteArray_maplEstringcOintgR(void *p);
   static void destruct_maplEstringcOintgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const map<string,int>*)
   {
      map<string,int> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,int>),0);
      static ::ROOT::TGenericClassInfo 
         instance("map<string,int>", -2, "map.dll", 0,
                  typeid(map<string,int>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &maplEstringcOintgR_Dictionary, isa_proxy, 0,
                  sizeof(map<string,int>) );
      instance.SetNew(&new_maplEstringcOintgR);
      instance.SetNewArray(&newArray_maplEstringcOintgR);
      instance.SetDelete(&delete_maplEstringcOintgR);
      instance.SetDeleteArray(&deleteArray_maplEstringcOintgR);
      instance.SetDestructor(&destruct_maplEstringcOintgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::MapInsert< map<string,int> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const map<string,int>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void maplEstringcOintgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const map<string,int>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_maplEstringcOintgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,int> : new map<string,int>;
   }
   static void *newArray_maplEstringcOintgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,int>[nElements] : new map<string,int>[nElements];
   }
   // Wrapper around operator delete
   static void delete_maplEstringcOintgR(void *p) {
      delete ((map<string,int>*)p);
   }
   static void deleteArray_maplEstringcOintgR(void *p) {
      delete [] ((map<string,int>*)p);
   }
   static void destruct_maplEstringcOintgR(void *p) {
      typedef map<string,int> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class map<string,int>

namespace ROOTDict {
   void maplEstringcOstringgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void maplEstringcOstringgR_Dictionary();
   static void *new_maplEstringcOstringgR(void *p = 0);
   static void *newArray_maplEstringcOstringgR(Long_t size, void *p);
   static void delete_maplEstringcOstringgR(void *p);
   static void deleteArray_maplEstringcOstringgR(void *p);
   static void destruct_maplEstringcOstringgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const map<string,string>*)
   {
      map<string,string> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,string>),0);
      static ::ROOT::TGenericClassInfo 
         instance("map<string,string>", -2, "prec_stl/map", 63,
                  typeid(map<string,string>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &maplEstringcOstringgR_Dictionary, isa_proxy, 0,
                  sizeof(map<string,string>) );
      instance.SetNew(&new_maplEstringcOstringgR);
      instance.SetNewArray(&newArray_maplEstringcOstringgR);
      instance.SetDelete(&delete_maplEstringcOstringgR);
      instance.SetDeleteArray(&deleteArray_maplEstringcOstringgR);
      instance.SetDestructor(&destruct_maplEstringcOstringgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::MapInsert< map<string,string> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const map<string,string>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void maplEstringcOstringgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const map<string,string>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_maplEstringcOstringgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,string> : new map<string,string>;
   }
   static void *newArray_maplEstringcOstringgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,string>[nElements] : new map<string,string>[nElements];
   }
   // Wrapper around operator delete
   static void delete_maplEstringcOstringgR(void *p) {
      delete ((map<string,string>*)p);
   }
   static void deleteArray_maplEstringcOstringgR(void *p) {
      delete [] ((map<string,string>*)p);
   }
   static void destruct_maplEstringcOstringgR(void *p) {
      typedef map<string,string> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class map<string,string>

namespace ROOTDict {
   void vectorlEstringgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEstringgR_Dictionary();
   static void *new_vectorlEstringgR(void *p = 0);
   static void *newArray_vectorlEstringgR(Long_t size, void *p);
   static void delete_vectorlEstringgR(void *p);
   static void deleteArray_vectorlEstringgR(void *p);
   static void destruct_vectorlEstringgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<string>*)
   {
      vector<string> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<string>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<string>", -2, "prec_stl/vector", 49,
                  typeid(vector<string>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlEstringgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<string>) );
      instance.SetNew(&new_vectorlEstringgR);
      instance.SetNewArray(&newArray_vectorlEstringgR);
      instance.SetDelete(&delete_vectorlEstringgR);
      instance.SetDeleteArray(&deleteArray_vectorlEstringgR);
      instance.SetDestructor(&destruct_vectorlEstringgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<string> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<string>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEstringgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<string>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlEstringgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<string> : new vector<string>;
   }
   static void *newArray_vectorlEstringgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<string>[nElements] : new vector<string>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEstringgR(void *p) {
      delete ((vector<string>*)p);
   }
   static void deleteArray_vectorlEstringgR(void *p) {
      delete [] ((vector<string>*)p);
   }
   static void destruct_vectorlEstringgR(void *p) {
      typedef vector<string> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<string>

/********************************************************
* /home/stowell/t2krep/NIWG/externalDataFitter/src/Utils/_ROOT_DICT_ExternalDataFit_Utils.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtable_ROOT_DICT_ExternalDataFit_Utils();

extern "C" void G__set_cpp_environment_ROOT_DICT_ExternalDataFit_Utils() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("FitLogger.h");
  G__add_compiledheader("FitParameters.h");
  G__add_compiledheader("FitUtils.h");
  G__add_compiledheader("PlotUtils.h");
  G__add_compiledheader("SignalDef.h");
  G__add_compiledheader("StatUtils.h");
  G__cpp_reset_tagtable_ROOT_DICT_ExternalDataFit_Utils();
}
#include <new>
extern "C" int G__cpp_dllrev_ROOT_DICT_ExternalDataFit_Utils() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* FitPar */
static int G___ROOT_DICT_ExternalDataFit_Utils_168_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const FitParameters& obj = FitPar::Config();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_ExternalDataFit_Utils_168_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         string* pobj;
         string xobj = FitPar::GetDataBase();
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_ExternalDataFit_Utils_168_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         string* pobj;
         string xobj = FitPar::GetNIWGData();
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}


/* FitParameters */
static int G___ROOT_DICT_ExternalDataFit_Utils_546_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const FitParameters& obj = FitParameters::GetParams();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_ExternalDataFit_Utils_546_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   FitParameters* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new FitParameters[n];
     } else {
       p = new((void*) gvp) FitParameters[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new FitParameters;
     } else {
       p = new((void*) gvp) FitParameters;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_FitParameters));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_ExternalDataFit_Utils_546_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitParameters*) G__getstructoffset())->SetParamFile(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_ExternalDataFit_Utils_546_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitParameters*) G__getstructoffset())->ReadParamFile(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_ExternalDataFit_Utils_546_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitParameters*) G__getstructoffset())->ForceParam(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_ExternalDataFit_Utils_546_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitParameters*) G__getstructoffset())->SetParB(*((string*) G__int(libp->para[0])), (bool) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_ExternalDataFit_Utils_546_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitParameters*) G__getstructoffset())->SetParD(*((string*) G__int(libp->para[0])), (double) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_ExternalDataFit_Utils_546_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitParameters*) G__getstructoffset())->SetParI(*((string*) G__int(libp->para[0])), (int) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_ExternalDataFit_Utils_546_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((FitParameters*) G__getstructoffset())->GetParI(*((string*) G__int(libp->para[0]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_ExternalDataFit_Utils_546_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((FitParameters*) G__getstructoffset())->GetParB(*((string*) G__int(libp->para[0]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_ExternalDataFit_Utils_546_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((FitParameters*) G__getstructoffset())->GetParD(*((string*) G__int(libp->para[0]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_ExternalDataFit_Utils_546_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         string* pobj;
         string xobj = ((FitParameters*) G__getstructoffset())->GetParS(*((string*) G__int(libp->para[0])));
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_ExternalDataFit_Utils_546_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         string* pobj;
         string xobj = ((FitParameters*) G__getstructoffset())->GetAllParametersArg();
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_ExternalDataFit_Utils_546_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitParameters*) G__getstructoffset())->MakeParameterCard(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G___ROOT_DICT_ExternalDataFit_Utils_546_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((FitParameters*) G__getstructoffset())->Write();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G___ROOT_DICT_ExternalDataFit_Utils_546_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   FitParameters* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new FitParameters(*(FitParameters*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_FitParameters));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef FitParameters G__TFitParameters;
static int G___ROOT_DICT_ExternalDataFit_Utils_546_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (FitParameters*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((FitParameters*) (soff+(sizeof(FitParameters)*i)))->~G__TFitParameters();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (FitParameters*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((FitParameters*) (soff))->~G__TFitParameters();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G___ROOT_DICT_ExternalDataFit_Utils_546_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   FitParameters* dest = (FitParameters*) G__getstructoffset();
   *dest = *(FitParameters*) libp->para[0].ref;
   const FitParameters& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* FitPar */

/* FitParameters */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfunc_ROOT_DICT_ExternalDataFit_Utils {
 public:
  G__Sizep2memfunc_ROOT_DICT_ExternalDataFit_Utils(): p(&G__Sizep2memfunc_ROOT_DICT_ExternalDataFit_Utils::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfunc_ROOT_DICT_ExternalDataFit_Utils::*p)();
};

size_t G__get_sizep2memfunc_ROOT_DICT_ExternalDataFit_Utils()
{
  G__Sizep2memfunc_ROOT_DICT_ExternalDataFit_Utils a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritance_ROOT_DICT_ExternalDataFit_Utils() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetable_ROOT_DICT_ExternalDataFit_Utils() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,std::string>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,std::string>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,string>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,string,less<string> >",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,int>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,int>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,double>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,double>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,bool>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,bool>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,bool>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,bool,less<string> >",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::string>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<FitParticle>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlEFitParticlecOallocatorlEFitParticlegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_reverse_iteratorlEvectorlEFitParticlecOallocatorlEFitParticlegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlEFitParticlecOallocatorlEFitParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_reverse_iteratorlEvectorlEFitParticlecOallocatorlEFitParticlegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlEFitParticlecOallocatorlEFitParticlegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSym<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSymlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTColumn_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTFlat_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSub_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTColumnlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTFlatlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSublEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TElementActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TElementPosActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparse<Double_t>",117,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* FitPar */
static void G__setup_memvarFitPar(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_FitPar));
   {
   G__memvar_setup((void*)(&FitPar::log_verb),104,0,0,-1,-1,-1,1,"log_verb=",0,"!< Current VERBOSITY");
   G__memvar_setup((void*)(&FitPar::err_verb),104,0,0,-1,-1,-1,1,"err_verb=",0,"!< Current ERROR VERBOSITY");
   G__memvar_setup((void*)(&FitPar::use_colors),103,0,0,-1,-1,-1,1,"use_colors=",0,"!< Use BASH Terminal Colors Flag");
   G__memvar_setup((void*)(&FitPar::super_rainbow_mode),103,0,0,-1,-1,-1,1,"super_rainbow_mode=",0,"!< For when fitting gets boring.");
   G__memvar_setup((void*)(&FitPar::super_rainbow_mode_colour),104,0,0,-1,-1,-1,1,"super_rainbow_mode_colour=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* FitParameters */
static void G__setup_memvarFitParameters(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_FitParameters));
   { FitParameters *p; p=(FitParameters*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->parFileName)-(long)(p)),117,0,0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_string),-1,-1,1,"parFileName=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->parameterMap_all)-(long)(p)),117,0,0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),G__defined_typename("map<std::string,std::string>"),-1,1,"parameterMap_all=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->variables)-(long)(p)),105,0,0,-1,-1,-1,1,"variables=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nuwro_enabled)-(long)(p)),103,0,0,-1,-1,-1,1,"nuwro_enabled=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->out)-(long)(p)),85,0,0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TFile),-1,-1,1,"out=",0,"pointer to output file");
   G__memvar_setup((void*)((long)(&p->outputname)-(long)(p)),117,0,0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_string),-1,-1,1,"outputname=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->parameterMap_int)-(long)(p)),117,0,0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),G__defined_typename("map<std::string,int>"),-1,1,"parameterMap_int=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->parameterMap_double)-(long)(p)),117,0,0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),G__defined_typename("map<std::string,double>"),-1,1,"parameterMap_double=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->parameterMap_string)-(long)(p)),117,0,0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),G__defined_typename("map<std::string,std::string>"),-1,1,"parameterMap_string=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->parameterMap_bool)-(long)(p)),117,0,0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),G__defined_typename("map<std::string,bool>"),-1,1,"parameterMap_bool=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->parNames)-(long)(p)),117,0,0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlEstringcOallocatorlEstringgRsPgR),G__defined_typename("vector<std::string>"),-1,1,"parNames=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->parValues)-(long)(p)),117,0,0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlEstringcOallocatorlEstringgRsPgR),G__defined_typename("vector<std::string>"),-1,1,"parValues=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->cardLines)-(long)(p)),117,0,0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlEstringcOallocatorlEstringgRsPgR),G__defined_typename("vector<std::string>"),-1,1,"cardLines=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->iteration)-(long)(p)),105,0,0,-1,-1,-1,1,"iteration=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_FitParameters),-1,-2,2,"m_fitparameterInstance=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvar_ROOT_DICT_ExternalDataFit_Utils() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncFitPar(void) {
   /* FitPar */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_FitPar));
   G__memfunc_setup("Config",598,G___ROOT_DICT_ExternalDataFit_Utils_168_0_1, 117, G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_FitParameters), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) G__func2void( (FitParameters& (*)())(&FitPar::Config) ), 0);
   G__memfunc_setup("GetDataBase",1045,G___ROOT_DICT_ExternalDataFit_Utils_168_0_2, 117, G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_string), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) G__func2void( (string (*)())(&FitPar::GetDataBase) ), 0);
   G__memfunc_setup("GetNIWGData",975,G___ROOT_DICT_ExternalDataFit_Utils_168_0_3, 117, G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_string), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) G__func2void( (string (*)())(&FitPar::GetNIWGData) ), 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncFitParameters(void) {
   /* FitParameters */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_FitParameters));
   G__memfunc_setup("GetParams",900,G___ROOT_DICT_ExternalDataFit_Utils_546_0_1, 117, G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_FitParameters), -1, 1, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (FitParameters& (*)())(&FitParameters::GetParams) ), 0);
   G__memfunc_setup("FitParameters",1335,G___ROOT_DICT_ExternalDataFit_Utils_546_0_2, 105, G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_FitParameters), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetParamFile",1181,G___ROOT_DICT_ExternalDataFit_Utils_546_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - fileName", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadParamFile",1261,G___ROOT_DICT_ExternalDataFit_Utils_546_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - fileName", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ForceParam",992,G___ROOT_DICT_ExternalDataFit_Utils_546_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - parOption", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetParB",657,G___ROOT_DICT_ExternalDataFit_Utils_546_0_6, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'string' - 0 - parName g - - 0 - val", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetParD",659,G___ROOT_DICT_ExternalDataFit_Utils_546_0_7, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'string' - 0 - parName d - - 0 - val", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetParI",664,G___ROOT_DICT_ExternalDataFit_Utils_546_0_8, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'string' - 0 - parName i - - 0 - val", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetParI",652,G___ROOT_DICT_ExternalDataFit_Utils_546_0_9, 105, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - parName", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetParB",645,G___ROOT_DICT_ExternalDataFit_Utils_546_0_10, 103, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - parName", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetParD",647,G___ROOT_DICT_ExternalDataFit_Utils_546_0_11, 100, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - parName", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetParS",662,G___ROOT_DICT_ExternalDataFit_Utils_546_0_12, 117, G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_string), -1, 0, 1, 1, 1, 0, "u 'string' - 0 - parName", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetAllParametersArg",1895,G___ROOT_DICT_ExternalDataFit_Utils_546_0_13, 117, G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_string), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MakeParameterCard",1689,G___ROOT_DICT_ExternalDataFit_Utils_546_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Write",523,G___ROOT_DICT_ExternalDataFit_Utils_546_0_15, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("FitParameters", 1335, G___ROOT_DICT_ExternalDataFit_Utils_546_0_16, (int) ('i'), G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_FitParameters), -1, 0, 1, 1, 1, 0, "u 'FitParameters' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~FitParameters", 1461, G___ROOT_DICT_ExternalDataFit_Utils_546_0_17, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G___ROOT_DICT_ExternalDataFit_Utils_546_0_18, (int) ('u'), G__get_linked_tagnum(&G___ROOT_DICT_ExternalDataFit_UtilsLN_FitParameters), -1, 1, 1, 1, 1, 0, "u 'FitParameters' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfunc_ROOT_DICT_ExternalDataFit_Utils() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_global_ROOT_DICT_ExternalDataFit_Utils() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {
}

static void G__cpp_setup_func30() {
}

static void G__cpp_setup_func31() {
}

static void G__cpp_setup_func32() {
}

static void G__cpp_setup_func33() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_func_ROOT_DICT_ExternalDataFit_Utils() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
  G__cpp_setup_func30();
  G__cpp_setup_func31();
  G__cpp_setup_func32();
  G__cpp_setup_func33();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_string = { "string" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_FitPar = { "FitPar" , 110 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR = { "map<string,int,less<string>,allocator<pair<const string,int> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR = { "map<string,double,less<string>,allocator<pair<const string,double> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_FitParameters = { "FitParameters" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR = { "map<string,string,less<string>,allocator<pair<const string,string> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR = { "map<string,bool,less<string>,allocator<pair<const string,bool> > >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TElementActionTlEdoublegR = { "TElementActionT<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TElementPosActionTlEdoublegR = { "TElementPosActionT<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlEFitParticlecOallocatorlEFitParticlegRsPgR = { "vector<FitParticle,allocator<FitParticle> >" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_reverse_iteratorlEvectorlEFitParticlecOallocatorlEFitParticlegRsPgRcLcLiteratorgR = { "reverse_iterator<vector<FitParticle,allocator<FitParticle> >::iterator>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSymlEdoublegR = { "TMatrixTSym<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTlEdoublegR = { "TMatrixT<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparselEdoublegR = { "TMatrixTSparse<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTRow_constlEdoublegR = { "TMatrixTRow_const<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTRowlEdoublegR = { "TMatrixTRow<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTDiag_constlEdoublegR = { "TMatrixTDiag_const<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTColumn_constlEdoublegR = { "TMatrixTColumn_const<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTFlat_constlEdoublegR = { "TMatrixTFlat_const<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSub_constlEdoublegR = { "TMatrixTSub_const<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseRow_constlEdoublegR = { "TMatrixTSparseRow_const<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseDiag_constlEdoublegR = { "TMatrixTSparseDiag_const<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTColumnlEdoublegR = { "TMatrixTColumn<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTDiaglEdoublegR = { "TMatrixTDiag<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTFlatlEdoublegR = { "TMatrixTFlat<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSublEdoublegR = { "TMatrixTSub<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseRowlEdoublegR = { "TMatrixTSparseRow<double>" , 99 , -1 };
G__linked_taginfo G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseDiaglEdoublegR = { "TMatrixTSparseDiag<double>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtable_ROOT_DICT_ExternalDataFit_Utils() {
  G___ROOT_DICT_ExternalDataFit_UtilsLN_string.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_FitPar.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TFile.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TVectorTlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TVectorTlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_FitParameters.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TElementActionTlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TElementPosActionTlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlEFitParticlecOallocatorlEFitParticlegRsPgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_reverse_iteratorlEvectorlEFitParticlecOallocatorlEFitParticlegRsPgRcLcLiteratorgR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSymlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparselEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTRow_constlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTRowlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTDiag_constlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTColumn_constlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTFlat_constlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSub_constlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseRow_constlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseDiag_constlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTColumnlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTDiaglEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTFlatlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSublEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseRowlEdoublegR.tagnum = -1 ;
  G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseDiaglEdoublegR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtable_ROOT_DICT_ExternalDataFit_Utils() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_string);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_FitPar),0,-1,0,(char*)NULL,G__setup_memvarFitPar,G__setup_memfuncFitPar);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TFile);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TVectorTlEdoublegR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_FitParameters),sizeof(FitParameters),-1,263424,(char*)NULL,G__setup_memvarFitParameters,G__setup_memfuncFitParameters);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TElementActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TElementPosActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_vectorlEFitParticlecOallocatorlEFitParticlegRsPgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_reverse_iteratorlEvectorlEFitParticlecOallocatorlEFitParticlegRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSymlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparselEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTColumn_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTFlat_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSub_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTColumnlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTFlatlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSublEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G___ROOT_DICT_ExternalDataFit_UtilsLN_TMatrixTSparseDiaglEdoublegR);
}
extern "C" void G__cpp_setup_ROOT_DICT_ExternalDataFit_Utils(void) {
  G__check_setup_version(30051515,"G__cpp_setup_ROOT_DICT_ExternalDataFit_Utils()");
  G__set_cpp_environment_ROOT_DICT_ExternalDataFit_Utils();
  G__cpp_setup_tagtable_ROOT_DICT_ExternalDataFit_Utils();

  G__cpp_setup_inheritance_ROOT_DICT_ExternalDataFit_Utils();

  G__cpp_setup_typetable_ROOT_DICT_ExternalDataFit_Utils();

  G__cpp_setup_memvar_ROOT_DICT_ExternalDataFit_Utils();

  G__cpp_setup_memfunc_ROOT_DICT_ExternalDataFit_Utils();
  G__cpp_setup_global_ROOT_DICT_ExternalDataFit_Utils();
  G__cpp_setup_func_ROOT_DICT_ExternalDataFit_Utils();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfunc_ROOT_DICT_ExternalDataFit_Utils();
  return;
}
class G__cpp_setup_init_ROOT_DICT_ExternalDataFit_Utils {
  public:
    G__cpp_setup_init_ROOT_DICT_ExternalDataFit_Utils() { G__add_setup_func("_ROOT_DICT_ExternalDataFit_Utils",(G__incsetup)(&G__cpp_setup_ROOT_DICT_ExternalDataFit_Utils)); G__call_setup_funcs(); }
   ~G__cpp_setup_init_ROOT_DICT_ExternalDataFit_Utils() { G__remove_setup_func("_ROOT_DICT_ExternalDataFit_Utils"); }
};
G__cpp_setup_init_ROOT_DICT_ExternalDataFit_Utils G__cpp_setup_initializer_ROOT_DICT_ExternalDataFit_Utils;

