#!/bin/bash

set -e

source $(nuis internal valid.funcs)
nuis_valid_parse_argments ${@}

EXP=SciBooNE

for SAMP in \
            SciBooNE_CCCOH_STOP_NTrks_nu \
            SciBooNE_CCCOH_1TRK_1DQ2_nu \
            SciBooNE_CCCOH_1TRK_1Dpmu_nu \
            SciBooNE_CCCOH_1TRK_1Dthetamu_nu \
            SciBooNE_CCCOH_MuPr_1DQ2_nu \
            SciBooNE_CCCOH_MuPr_1Dpmu_nu \
            SciBooNE_CCCOH_MuPr_1Dthetamu_nu \
            SciBooNE_CCCOH_MuPiVA_1DQ2_nu \
            SciBooNE_CCCOH_MuPiVA_1Dpmu_nu \
            SciBooNE_CCCOH_MuPiVA_1Dthetamu_nu \
            SciBooNE_CCCOH_MuPiNoVA_1DQ2_nu \
            SciBooNE_CCCOH_MuPiNoVA_1Dthetapr_nu \
            SciBooNE_CCCOH_MuPiNoVA_1Dthetapi_nu \
            SciBooNE_CCCOH_MuPiNoVA_1Dthetamu_nu \
            SciBooNE_CCCOH_MuPiNoVA_1Dpmu_nu \
            SciBooNE_CCCOH_STOPFINAL_1DQ2_nu \
            SciBooNE_CCInc_XSec_1DEnu_nu \
            SciBooNE_CCInc_XSec_1DEnu_nu_NEUT \
            SciBooNE_CCInc_XSec_1DEnu_nu_NUANCE \
            ; do

    nuis plot --chi2 -i $(nuis_gen_tag_list ${EXP} nu.numu.CH.comp.root) \
        -s ${SAMP} --mc-tag ${GENTAGLIST[@]}

done

nuis plot collate \
    -s SciBooNE_CCCOH_STOP_NTrks_nu \
    -s SciBooNE_CCCOH_1TRK_1DQ2_nu \
    -s SciBooNE_CCCOH_1TRK_1Dpmu_nu \
    -s SciBooNE_CCCOH_1TRK_1Dthetamu_nu \
    -s SciBooNE_CCCOH_MuPr_1DQ2_nu \
    -s SciBooNE_CCCOH_MuPr_1Dpmu_nu \
    -s SciBooNE_CCCOH_MuPr_1Dthetamu_nu \
    -s SciBooNE_CCCOH_MuPiVA_1DQ2_nu \
    -s SciBooNE_CCCOH_MuPiVA_1Dpmu_nu \
    -s SciBooNE_CCCOH_MuPiVA_1Dthetamu_nu \
    -s SciBooNE_CCCOH_MuPiNoVA_1DQ2_nu \
    -s SciBooNE_CCCOH_MuPiNoVA_1Dthetapr_nu \
    -s SciBooNE_CCCOH_MuPiNoVA_1Dthetapi_nu \
    -s SciBooNE_CCCOH_MuPiNoVA_1Dthetamu_nu \
    -s SciBooNE_CCCOH_MuPiNoVA_1Dpmu_nu \
    -s SciBooNE_CCCOH_STOPFINAL_1DQ2_nu \
    -s SciBooNE_CCInc_XSec_1DEnu_nu \
    -s SciBooNE_CCInc_XSec_1DEnu_nu_NEUT \
    -s SciBooNE_CCInc_XSec_1DEnu_nu_NUANCE \
 -m ${GENTAGLIST[@]} -o SciBooNE_validations.tex

