#!/bin/bash

set -e

source $(nuis internal valid.funcs)
nuis_valid_parse_argments ${@}
nuis_check_gen_enabled ${GENLIST[@]}

EXP=FNAL

for (( i=0; i < ${#GENLIST[@]}; ++i )); do
    GEN=${GENLIST[${i}]}
    GENTAG=${GENTAGLIST[${i}]}

    if [ ! -e ${EXP}.${GENTAG}.nu.numu.D2.comp.root ] || [ "${NUIS_FORCE}" == "ON" ]; then
        nuis comp ${EXP}.${GENTAG}.nu.numu.D2.root \
            -f -t ${GEN} \
            -o ${EXP}.${GENTAG}.nu.numu.D2.comp.root \
                -s FNAL_CCQE_Evt_1DQ2_nu \
                -s FNAL_CC1ppip_XSec_1DEnu_nu \
                -s FNAL_CC1ppip_XSec_1DQ2_nu \
                -s FNAL_CC1ppip_Evt_1DQ2_nu \
            --config UseSVDInverse=1
    fi

done

for (( i=0; i < ${#GENLIST[@]}; ++i )); do
    GEN=${GENLIST[${i}]}
    GENTAG=${GENTAGLIST[${i}]}

    if [ ! -e ${EXP}.${GENTAG}.nubar.numubar.D2.comp.root ] || [ "${NUIS_FORCE}" == "ON" ]; then
        nuis comp ${EXP}.${GENTAG}.nubar.numubar.D2.root \
            -f -t ${GEN} \
            -o ${EXP}.${GENTAG}.nubar.numubar.D2.comp.root \
                -s FNAL_CC1ppim_XSec_1DEnu_antinu \
            --config UseSVDInverse=1
    fi

done