#!/bin/bash
set -e

source $(nuis internal valid.funcs)
nuis_valid_parse_argments "${@}"
nuis_check_gen_enabled "${GENLIST[@]}"

EXP=BNL
NEVENTS=250000

#numu
for TARGET in D2; do
    for (( i=0; i < ${#GENLIST[@]}; ++i )); do
        GEN=${GENLIST[${i}]}
        GENTAG=${GENTAGLIST[${i}]}
        if [ ! -e "${EXP}.${GENTAG}.nu.numu.${TARGET}.root" ] || [ "${NUIS_FORCE}" == "ON" ]; then
            nuis gen ${GEN} -o ${EXP}.${GENTAG}.nu.numu.${TARGET}.root \
                            -t ${TARGET} \
                            -M nu \
                            -P numu \
                            -n ${NEVENTS} \
                            -E ${EXP} "${GENARGS[@]}"
        fi
    done
done