if(NOT COMMAND EnsureVarOrEnvSet)
function(EnsureVarOrEnvSet VARNAME ENVNAME)
  if(NOT DEFINED ${VARNAME} OR "${${VARNAME}}x" STREQUAL "x")
    if(DEFINED ENV{${ENVNAME}} AND NOT "$ENV{${ENVNAME}}x" STREQUAL "x")
      set(${VARNAME} $ENV{${ENVNAME}} PARENT_SCOPE)
    endif()
  else()
    cmessage(FATAL_ERROR "${VARNAME} undefined, either configure with -D${VARNAME}=<value> or set ${ENVNAME} into the environment")
  endif()
endfunction()
endif()
