if(NOT COMMAND DefineEnabledRequiredSwitch)
  function(DefineEnabledRequiredSwitch VARNAME)
    if(NOT DEFINED ${VARNAME}_ENABLED OR "${${VARNAME}_ENABLED}x" STREQUAL "x")
      SET(${VARNAME}_ENABLED TRUE PARENT_SCOPE)
      SET(${VARNAME}_ENABLED TRUE)
    else()
      SET(${VARNAME}_REQUIRED ${${VARNAME}_ENABLED} PARENT_SCOPE)
      SET(${VARNAME}_REQUIRED ${${VARNAME}_ENABLED})
    endif()
  endfunction()
endif()