if(USE_NUHEPMC)

  execute_process (COMMAND NuHepMC-config --incdir
    OUTPUT_VARIABLE NUHEPMC_INCDIR OUTPUT_STRIP_TRAILING_WHITESPACE)

  execute_process (COMMAND NuHepMC-config --libdir
    OUTPUT_VARIABLE NUHEPMC_LIBDIR OUTPUT_STRIP_TRAILING_WHITESPACE)

  execute_process (COMMAND NuHepMC-config --prefix
    OUTPUT_VARIABLE NUHEPMC_ROOT OUTPUT_STRIP_TRAILING_WHITESPACE)


  execute_process (COMMAND HepMC3-config --includedir
    OUTPUT_VARIABLE HEPMC_INCDIR OUTPUT_STRIP_TRAILING_WHITESPACE)

  execute_process (COMMAND HepMC3-config --libdir
    OUTPUT_VARIABLE HEPMC_LIBDIR OUTPUT_STRIP_TRAILING_WHITESPACE)

  execute_process (COMMAND HepMC3-config --prefix
    OUTPUT_VARIABLE HEPMC_ROOT OUTPUT_STRIP_TRAILING_WHITESPACE)

  include_directories(${NUHEPMC_INCDIR})
  LIST(APPEND EXTRA_LINK_DIRS ${NUHEPMC_LIBDIR})
  LIST(APPEND EXTRA_LIBS NuHepMC)

  include_directories(${HEPMC_INCDIR})
  LIST(APPEND EXTRA_LINK_DIRS ${HEPMC_LIBDIR})
  LIST(APPEND EXTRA_LIBS HepMC3 HepMC3rootIO)

  LIST(APPEND EXTRA_CXX_FLAGS -D__NUHEPMCENABLED__)

  set(USE_NUHEPMC TRUE)

endif()
