function(BuildFlagString OUTPUTLIST DELIMITER)
  LIST(APPEND INPUT_LIST ${ARGN})
  if(NOT DELIMITER STREQUAL "")
    string(STRIP ${DELIMITER} DELIMITER)
  endif()
  if(NOT "${INPUT_LIST}" STREQUAL "")
    string(REPLACE ";" " ${DELIMITER}" LIST_STR "${DELIMITER}${INPUT_LIST}")
    string(STRIP "${LIST_STR}" LIST_STR)
    set(${OUTPUTLIST} ${LIST_STR} PARENT_SCOPE)
  else()
      set(${OUTPUTLIST} PARENT_SCOPE)
  endif()
endfunction()

#Here we want to look for linker flags in a list of libraries and escape them
function(BuildLibraryFlagString OUTPUTLIST)
  set(INPUT_LIST ${ARGN})
  BuildFlagString(NEED_SCRUB_LINKOPTS "-l" ${INPUT_LIST})
  string(REPLACE "-l-" "-" LIST_STR ${NEED_SCRUB_LINKOPTS})
  set(${OUTPUTLIST} ${LIST_STR} PARENT_SCOPE)
endfunction()

function(CatStringsIfNotEmpty OUTPUT_STRING)
  set(BUILD_STR)
  foreach(I ${ARGN})
    if(NOT I STREQUAL "")
      set(BUILD_STR "${BUILD_STR} ${I}")
    endif()
  endforeach()
  if(NOT BUILD_STR STREQUAL "")
    string(STRIP "${BUILD_STR}" BUILD_STR)
  endif()
  set(${OUTPUT_STRING} ${BUILD_STR} PARENT_SCOPE)
endfunction()

function(PrefixList OUTPUT_LIST PREFIX)
  set(${OUTPUT_LIST})
  foreach(I ${ARGN})
    if(NOT I STREQUAL "")
      LIST(APPEND ${OUTPUT_LIST} "${PREFIX}${I}")
    endif()
  endforeach()
  set(${OUTPUT_LIST} ${${OUTPUT_LIST}} PARENT_SCOPE)
endfunction()
